doc: Add the MQTT integration guide for Eclipse Paho client
TheThingsNetwork/lorawan-stack pull request #3128
Opened 2020-08-24 15:04 UTC by nejraselimovic

#### Summary
Adding the documentation for integration with Eclipse Paho.
Reference: https://github.com/TheThingsNetwork/lorawan-stack/issues/3106

#### Testing
Tested with Paho client running on a local machine and a CH TTS deployment.

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-07 09:32 UTC, benolayinka requested changes
Please consolidate the sections in to one, with #Publishing Downlink Messages and #Subscribing to Upstream Traffic sections. I did this for https://github.com/TheThingsNetwork/lorawan-stack/pull/3148#pullrequestreview-483403952 as an example

2020-09-09 09:36 UTC, nejraselimovic commented
> Please consolidate the sections in to one, with #Publishing Downlink Messages and #Subscribing to Upstream Traffic sections. I did this for [#3148 (review)](https://github.com/TheThingsNetwork/lorawan-stack/pull/3148#pullrequestreview-483403952) as an example

Done, please approve if that's all

2020-09-14 13:33 UTC, benolayinka approved these changes

2020-09-14 13:33 UTC, benolayinka commented on doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
> +command in the terminal.
```suggestion
```

2020-09-14 13:33 UTC, benolayinka commented on doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
> +The list containing `msg_count` messages published during the default 60 seconds period will be shown in the terminal as a result of running this script.
```suggestion
Running this script will show the most recent `msg_count` messages published during the last 60 seconds.
```

2020-09-14 13:33 UTC, benolayinka commented on doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
> +In case you want to use TLS for security, change the port value to `8883` and pass the `tls` argument to the `simple` function according to its [definition](https://pypi.org/project/paho-mqtt/#id4),
```suggestion
To use TLS for security, change the port value to `8883` and pass the `tls` argument to the `simple` function according to its [definition](https://pypi.org/project/paho-mqtt/#id4), where `tls` has to at least contain the path to the CA certificate for your deployment.
```

2020-09-14 13:33 UTC, benolayinka commented on doc/content/integrations/mqtt-clients/eclipse-paho/_index.md
> +You will see the downlink message being scheduled in {{% tts %}} Console under **Live data** tab and your end device will receive the message in a short time.
```suggestion
You will see scheduled messages in the console under the **Live data** tab and your end device will receive the message after a short time.
```

2020-09-22 12:49 UTC, merged