doc: Add Chirpstack migration section to docs
TheThingsNetwork/lorawan-stack pull request #3205
Opened 2020-09-09 12:35 UTC by nejraselimovic

#### Summary
Adding instructions for exporting devices from Chirpstack.
Ref: https://github.com/TheThingsIndustries/lorawan-stack/issues/2329

#### Testing
Tested `ttn-lw-migrate` tool according to [these instructions](https://github.com/TheThingsIndustries/lorawan-stack-migrate/blob/master/README.md) with local TTS and Chirpstack deployments.

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-10 21:46 UTC, neoaggelos reviewed
Looking good, I see a few conflicts with #3197, so wait for @laurensslats review as well

2020-09-10 21:46 UTC, neoaggelos commented on doc/content/getting-started/migrating-from-networks/migrate-from-chirpstack.md
> +## Export Devices
Nit; End Devices, also in other places

2020-09-10 21:46 UTC, neoaggelos commented on doc/content/getting-started/migrating-from-networks/migrate-from-chirpstack.md
> +To export multiple applications to an `applications.json` file, you need to create a `.txt` file containing one application name per line and run the following command in your terminal:
"Multiple applications" is slightly misleading here, I would call it "export end devices from multiple applications"

2020-09-14 13:56 UTC, benolayinka approved these changes

2020-09-16 09:22 UTC, nejraselimovic commented
> Looking good, I see a few conflicts with #3197, so wait for @laurensslats review as well

These are fixed, so now just waiting for @laurensslats

2020-10-08 11:29 UTC, nejraselimovic commented
@benolayinka I see now that you already approved this, but can you please check this once again in the context of the [entire section](https://thethingsstack.io/getting-started/migrating-from-networks/) since Laurens is too busy?

2020-10-08 13:00 UTC, benolayinka requested changes
Moving this to docs repo

2020-10-08 13:00 UTC, benolayinka commented on doc/content/getting-started/migrating-from-networks/migrate-from-chirpstack.md
> +End devices and applications can easily be migrated from ChirpStack to {{% tts %}} with the `ttn-lw-migrate` tool. This tool is used for exporting end devices and applications to a [JSON file]({{< re
How do you install `ttn-lw-migrate` ?

2020-10-08 13:14 UTC, benolayinka commented
moved to new docs repo https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/27

2020-10-08 13:14 UTC, closed without merging