Add `ns redis application-uplink-queues gc` stack subcommand
TheThingsNetwork/lorawan-stack pull request #3225
Opened 2020-09-14 11:50 UTC by rvolosatovs

#### Summary

References #2908 

#### Changes

- Add `ns redis application-uplink-queues gc` stack subcommand

#### Testing

Start 3.9.1, generate a bunch of uplinks, switch to latest 3.9, generate a bunch of uplinks and run the tool

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-14 11:53 UTC, rvolosatovs commented on cmd/ttn-lw-stack/commands/redis.go
> +// Copyright © 2019 The Things Network Foundation, The Things Industries B.V.
will update to 2020

2020-09-14 11:56 UTC, KrishnaIyer commented
Can you add some documentation here;
- Necessary config. I don't think we need to dump the entire ns  config object for this tool right
- How often/under what conditions should this tool be run?

2020-09-14 12:00 UTC, rvolosatovs commented
>     * Necessary config. I don't think we need to dump the entire `ns`  config object for this tool right?

It requires configuration in `redis` namespace sufficient to create a client, that's it.
Logger configuration is required if you want to see output.

>     * How often/under what conditions should this tool be run?

When updating from 3.9.1 or below to a version above that. It should not be necessary in other cases, but that may change and I intend to add more GC subcommands here.

2020-09-14 12:09 UTC, johanstokking commented
This command is very specific for one use case whose use case is very conditional. Since we have the compatibility commitment on CLI, this is going to stay in V3 until the end of time.

Therefore, can we have a more general `ns-db prune` command, like we have `is-db` commands?

2020-09-14 12:25 UTC, rvolosatovs commented
> This command is very specific for one use case whose is very conditional. Since we have the compatibility commitment on CLI, this is going to stay in V3 until the end of time.
> 
> We may not have application uplink queues anymore, let alone Redis.
> 
> Therefore, can we have a more general `ns-db prune` command, like we have `is-db` commands?

We can extract this into a separate tool, but this is specific to Redis and application uplink queues. The intention is to add more subcommands to `ns` namespace.
`ns-db prune` apart from being ugly, requires then the CLI determine what storage backend is used automatically (error prone and unnecessary) and could potentially delete a lot of things we would not want to have deleted. The idea is to have, for example, utilities to handle stuck entries in streams (i.e. delivered to a consumer, but never acked due to failure), possible lock-contention etc. In any case, the whole point here is to be specific about Redis.

2020-09-14 12:26 UTC, rvolosatovs commented
So I'm fine with extracting this into `ns-redis-tool` or whatever, but definitely not `*-lw-stack ns-db prune`

2020-09-14 13:01 UTC, rvolosatovs commented
Can't we just make this subcommand hidden, such that customers can't depend on it?

2020-09-14 13:33 UTC, johanstokking commented
> `ns-db prune` apart from being ugly

What is ugly about it? We have `is-db` already, and `prune` is quite common. I find it more clear from a user perspective than `gc`

> requires then the CLI determine what storage backend is used automatically

`ttn-lw-stack` already does that based on config. It doesn't matter that NS currently only uses Redis from the user's perspective, like `is-db` is also generic and is not `ttn-lw-stack is postgresql insert-tenant` or something.

> and could potentially delete a lot of things we would not want to have deleted

That's going to be the magic of `prune`. And we can always make confirmations or flags should that be necessary. See https://docs.docker.com/engine/reference/commandline/system_prune/

> utilities to handle stuck entries in streams [...], possible lock-contention etc

If we need CLI to recover for these specific things, we're doing something wrong. We are not going to increase ops burden to manually fix these things and document everything.

2020-09-14 17:28 UTC, rvolosatovs commented
> What is ugly about it? We have `is-db` already, and `prune` is quite common. I find it more clear from a user perspective than `gc`

`is-db` or `ns-db` is. It should be `is db <command>` or just `is create-admin-user`, for example. The `-db` part is completely irrelevant and non-intuitive

2020-09-15 08:21 UTC, htdvisser requested changes

2020-09-15 08:21 UTC, htdvisser commented on cmd/ttn-lw-stack/commands/redis.go
> +		Short:   "Manage Network Server",
You may not agree with our historical choices for naming commands, but I think we can all agree that we prefer our commands to be consistent. So please instead write:

```
Use:   "ns-db",
Short: "Manage the Network Server database",
```

2020-09-15 11:46 UTC, johanstokking commented on cmd/ttn-lw-stack/commands/redis.go
> +					logger.WithError(err).Errorf("Failed to query groups of stream '%s'", k)
Isn't `gs` undefined at this point?

2020-09-15 11:46 UTC, johanstokking commented on cmd/ttn-lw-stack/commands/redis.go
> +						logger.Errorf("Unexpected consumer group with name '%s' found for stream '%s'", g.Name, k)
```suggestion
						logger.Errorf("Unexpected consumer group with name %q found for stream %q", g.Name, k)
```

2020-09-15 11:46 UTC, johanstokking commented on cmd/ttn-lw-stack/commands/redis.go
> +							logger.WithError(err).Errorf("Failed to XRANGE over stream '%s'", k)
```suggestion
							logger.WithError(err).Errorf("Failed to XRANGE over stream %q", k)
```

2020-09-15 11:46 UTC, johanstokking commented on cmd/ttn-lw-stack/commands/redis.go
> +							logger.WithError(err).Errorf("Failed to XDEL from stream '%s', continue to next stream", k)
```suggestion
							logger.WithError(err).Errorf("Failed to XDEL from stream %q, continue to next stream", k)
```

2020-09-15 11:52 UTC, htdvisser approved these changes

2020-09-15 13:15 UTC, rvolosatovs commented
@johanstokking

2020-09-15 13:16 UTC, johanstokking approved these changes

2020-09-15 13:17 UTC, merged