Send uplinks in the Console
TheThingsNetwork/lorawan-stack pull request #3266
Opened 2020-09-22 11:39 UTC by bafonins

#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/2234

<details>
<summary>Screenshots</summary>
<img width="603" alt="Screenshot 2020-09-22 at 13 57 22" src="https://user-images.githubusercontent.com/16374166/93876962-5a88a580-fce0-11ea-81dc-438c4c7013e6.png">
<img width="603" alt="Screenshot 2020-09-22 at 13 57 36" src="https://user-images.githubusercontent.com/16374166/93876967-5c526900-fce0-11ea-9b30-6dd162391def.png">

</details>

#### Changes

- Add `UplinkForm`
- Extend feature guards to check for `RIGHT_APPLICATION_TRAFFIC_UP_WRITE`
- Adapt UI for device messages to match device payload formatters UI
- Add `simulateUplink` method to the device service in the JS SDK

#### Testing

1. Sending uplinks with and without `RIGHT_APPLICATION_TRAFFIC_UP_WRITE`
2. Scheduling downlinks with and without `RIGHT_APPLICATION_TRAFFIC_DOWN_WRITE`
3. Sending uplinks/scheduling downlinks with both rights

##### Regressions

Device messages view

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-22 13:41 UTC, adriansmares approved these changes
LGTM

2020-09-22 16:03 UTC, kschiffer requested changes

2020-09-22 16:03 UTC, kschiffer commented on CHANGELOG.md
> +- Support for sedning end device uplinks in the Console.
```suggestion
- Support for sending end device uplinks in the Console.
```

2020-09-22 16:03 UTC, kschiffer commented on pkg/webui/console/components/downlink-form/downlink-form.js
> +          required
```suggestion
```

2020-09-22 16:03 UTC, kschiffer commented on pkg/webui/console/components/uplink-form/uplink-form.js
> +          required
```suggestion
```

2020-09-22 16:03 UTC, kschiffer commented on pkg/webui/console/views/device-messages/device-messages.js
> +      <IntlHelmet title={sharedMessages.messages} />
Let's use `Messaging` here instead of `Messages`. Looking at it again, it has too much the notion of being a data overview of messages. So that would be here and for the tab itself in the device overview.

cc @benolayinka please let us know if you have a more fitting term. This is about the title of the whole section where users can simulate uplinks and schedule downlinks.

2020-09-22 16:03 UTC, kschiffer commented on pkg/webui/console/views/device/index.js
>          title: sharedMessages.messages,
```suggestion
        title: sharedMessages.messaging,
```

See my other comment.

2020-09-22 16:03 UTC, kschiffer commented on pkg/webui/lib/shared-messages.js
> +  validateEvenLength: '{field} must be complete',
```suggestion
  validateEvenLength: '{field} must be a complete hex value',
```

2020-09-23 10:23 UTC, kschiffer approved these changes

2020-09-25 07:30 UTC, johanstokking commented
This is great stuff!

2020-09-25 10:42 UTC, merged