Join Server Application Activation Setting Registry
TheThingsNetwork/lorawan-stack pull request #3277
Opened 2020-09-23 21:10 UTC by rvolosatovs

#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack/issues/2322

#### Changes

- Add Join Server Application Activation Setting Registry
- Add `cryptoutil.UnwrapKeyEnvelope`
- Export `test.FormatError`
- Use `*ttnpb.KeyEnvelope` in `cryptoutil`
- Enforce that KEK is used if configured. Case when KEK label is non-empty and the KEK is missing in the Join Server now causes an error.

#### Testing

In-progress

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-23 21:14 UTC, rvolosatovs commented
@johanstokking feel free to take a look at the implementation already(it's pretty much final, unless I find bugs during testing), while I'm busy with testing

2020-09-25 18:53 UTC, rvolosatovs commented
@johanstokking the existing tests fail, because they depend on the fact that if configured KEK is missing, JS stores keys in plain-text. I do not think that it is in any way a sensible behavior - JS should never store keys in plain-text, especially if it's configured not to do so.
Do you agree with the proposed change?
Shall I refactor the existing tests then?

2020-10-01 07:24 UTC, johanstokking commented
@rvolosatovs if there's no encryption key for storage configured, what do you propose without breaking configuration?

2020-10-01 12:18 UTC, rvolosatovs commented
> @rvolosatovs if there's no encryption key for storage configured, what do you propose without breaking configuration?
> 
> The reason JS may store keys in the clear is that for some simple and small deployments, protecting the disk suffices. If you're using the Getting Started guide to setup a local network with a locally running Redis, there's very little added value in using KEKs.

If no key is configured - no encryption, however currently JS simply ignores the fact that key is configured if not present and that is the issue I'm pointing out here. In my opinion it's a bug, so it's fine to fix it here.

2020-10-01 12:21 UTC, rvolosatovs commented
So I mean things like these https://github.com/TheThingsNetwork/lorawan-stack/blob/b6b33e43d8232819f6f5046caa00544ea1137d10/pkg/joinserver/joinserver.go#L451-L454
I propose simply:
- If KEK label is configured - encrypt (and if corresponding KEK is missing - error)
- If KEK label is not configured - don't encrypt

2020-10-02 09:09 UTC, johanstokking commented
I see. Yes, that makes sense.

2020-10-12 19:49 UTC, rvolosatovs commented
> I see. Yes, that makes sense.

Ok, so with this approach, currently local joins fail with

```
  INFO Join not accepted                        dev_eui=DEADBEEF01020304 error=error:pkg/joinserver:wrap_key (failed to wrap key) error_cause=error:pkg/crypto/cryptoutil:kek_not_found (KEK with label `ns:localhost` not found) grpc_method=HandleJoin grpc_service=ttn.lorawan.v3.NsJs join_eui=01020304DEADBEEF label=ns:localhost namespace=joinserver request_id=01EMF5GVCHCKTYDS8EWW7PPWSR
```

What shall we do here then?
Since address-bound KEK is the default, I think it makes sense to check if address-bound KEK is present in the vault and if it is, encrypt - otherwise send plaintext. That means we'd have to extend `KeyVault` to expose `Contains(kekLabel string) (bool, error)` method

2020-10-13 10:46 UTC, johanstokking approved these changes

2020-10-13 14:26 UTC, johanstokking requested changes
I was too fast here, sorry about that.

> @rvolosatovs Since address-bound KEK is the default, I think it makes sense to check if address-bound KEK is present in the vault and if it is, encrypt - otherwise send plaintext. That means we'd have to extend `KeyVault` to expose `Contains(kekLabel string) (bool, error)` method

I'm not sure if we can and should add `Contains()` as some implementations may not support this or become quite expensive. Currently, wrapping is skipped when the key vault says "not found", which I believe is good behavior.

I don't entirely understand how this relates with AAS: that is not addressed based. If that application KEK doesn't exist, indeed we need to error, i.e. not continue and return plaintext.

2020-10-15 12:58 UTC, adriansmares approved these changes
LGTM but please wait for @johanstokking

2020-10-15 12:58 UTC, adriansmares commented on pkg/joinserver/grpc_application_activation_settings_registry.go
> +	JS       *JoinServer
Isn't it better to pass the registry and key vault here instead of tying it to the whole `JoinServer` struct ?

2020-10-15 14:38 UTC, rvolosatovs commented on pkg/joinserver/grpc_application_activation_settings_registry.go
> +	JS       *JoinServer
1. no
2. that's consistent with all the gRPC servers in this package

2020-10-19 07:34 UTC, htdvisser approved these changes

2020-10-19 09:23 UTC, johanstokking commented
@rvolosatovs is this ready for another pass? If so, request review.

I want the API in for 3.10, so adding a release blocker.

2020-10-19 09:31 UTC, johanstokking approved these changes

2020-10-19 09:31 UTC, johanstokking commented on pkg/joinserver/grpc_application_activation_settings_registry.go
> +	return ttnpb.Empty, err
```suggestion
	return ttnpb.Empty, nil
```

2020-10-19 10:23 UTC, merged