doc: Remove docs and tooling
TheThingsNetwork/lorawan-stack pull request #3297
Opened 2020-09-29 12:29 UTC by benolayinka

#### Summary

Remove docs and tooling, moved to https://github.com/TheThingsIndustries/lorawan-stack-docs

Will add a note in `tech-stack` to recompile `mage` to remove `docs` commands

Will also add a note to direct all future docs changes to https://github.com/TheThingsIndustries/lorawan-stack-docs

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-09-30 19:55 UTC, kschiffer requested changes
> Will add a note in `tech-stack` to recompile `mage` to remove `docs` commands

I guess this should be done in this PR as well.

2020-10-01 07:05 UTC, htdvisser approved these changes

2020-10-01 09:53 UTC, benolayinka commented
> > Will add a note in `tech-stack` to recompile `mage` to remove `docs` commands
> 
> I guess this should be done in this PR as well.

I don't think there's a way to force a recompile from within the repo. Everyone just has to do it themselves or they will get errors. @htdvisser ?

2020-10-01 10:09 UTC, kschiffer approved these changes

2020-10-01 11:38 UTC, merged