Add warning to frequency_plan_id field when selecting none
TheThingsNetwork/lorawan-stack pull request #3392
Opened 2020-10-21 13:57 UTC by mjamescompton

#### Summary

Closes #2805

Visuals are the same as https://github.com/TheThingsNetwork/lorawan-stack/pull/2992 just shows only after selected the field.

#### Changes

- Allow manually adding additional options to fetch select.
- Add `no-frequency-plan` value to frequency plan select
- Add warning message if `no-frequency-plan` is selected
- Remove `no-frequency-plan`  if selected before submitting form. 

#### Testing

Select `Do not use a frequency plan` in frequency plan dropdown. Try other values to check they can still be submitted 

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-10-22 11:59 UTC, bafonins requested changes

2020-10-22 11:59 UTC, bafonins commented on pkg/webui/console/components/gateway-data-form/index.js
> +    return Boolean(value === 'no-frequency-plan')
```suggestion
    return value === EMPTY_FREQ_PLAN
```

2020-10-22 11:59 UTC, bafonins commented on pkg/webui/console/containers/freq-plans-select/index.js
> +  none: 'Do not use a frequency plan',
```suggestion
  none: 'Do not set a frequency plan',
```

2020-10-22 11:59 UTC, bafonins commented on pkg/webui/console/containers/freq-plans-select/index.js
> +const additionalGsFrequencyPlans = [{ value: 'no-frequency-plan', label: m.none.defaultMessage }]
?
```suggestion
const additionalGsFrequencyPlans = [{ value: 'no-frequency-plan', label: m.none }]
```

2020-10-22 11:59 UTC, bafonins commented on pkg/webui/console/containers/fetch-select/index.js
> +  additionalOptions,
```suggestion
  additionalOptions = [],
```

This breaks e2e tests as not every usage of `CreateFetchSelect` has this parameter defined.

2020-10-26 12:18 UTC, kschiffer reviewed
Nothing to add.

2020-10-26 12:25 UTC, kschiffer requested changes
Actually, there are two UX problems:
- The warning should be displayed as soon as the "No frequency plan" option is selected (and not only when the field blurs)
- The warning should already appear initially, when the field is set to "No frequency plan" in the general settings

2020-10-27 15:36 UTC, mjamescompton commented
> The warning should already appear initially, when the field is set to "No frequency plan" in the general settings 

Just a note to myself to update the general settings form `onSubmit` to remove "No frequency plan" value so that its set as blank

2020-10-27 16:23 UTC, mjamescompton commented
Changing frequency plan from value to no value

2020-10-28 09:04 UTC, mjamescompton commented
@kschiffer  @bafonins Thought it was clearer to request review now before rebasing onto https://github.com/TheThingsNetwork/lorawan-stack/pull/3364. Let me know if you want me to do this first?

2020-10-28 10:27 UTC, bafonins commented
@mjamescompton please rebase

2020-11-04 09:46 UTC, kschiffer requested changes
Works as expected. See my remaining comment.

2020-11-04 09:46 UTC, kschiffer commented on pkg/webui/console/components/gateway-data-form/index.js
> +    setFieldTouched('frequency_plan_id')
Actually, I think we can mark select fields touched by default, when a value was selected:

```diff
diff --git a/pkg/webui/components/select/index.js b/pkg/webui/components/select/index.js
index 66822b752..b99fe50bb 100644
--- a/pkg/webui/components/select/index.js
+++ b/pkg/webui/components/select/index.js
@@ -105,7 +105,7 @@ class Select extends React.PureComponent {
       await this.setState({ value })
     }
 
-    onChange(value)
+    onChange(value, true)
   }
 
   @bind
```

2020-11-04 12:37 UTC, bafonins requested changes

2020-11-04 12:37 UTC, bafonins commented on pkg/webui/console/components/gateway-data-form/index.js
> +  isNoFrequencyPlan(value) {
```suggestion
  isEmptyFrequencyPlan(value) {
```

2020-11-04 12:37 UTC, bafonins commented on pkg/webui/console/components/gateway-data-form/index.js
> +  isNoFrequencyPlan(value) {
you can move it outside of the component class

2020-11-04 12:37 UTC, bafonins commented on pkg/webui/console/components/gateway-data-form/index.js
> +      showFrequencyPlanWarning: this.isNoFrequencyPlan(props.initialValues.freqPlan),
```suggestion
      showFrequencyPlanWarning: this.isNoFrequencyPlan(props.initialValues.frequency_plan_id) && props.update,
```

2020-11-04 12:37 UTC, bafonins commented on pkg/webui/console/components/gateway-data-form/index.js
> +    if (this.isNoFrequencyPlan(values.frequency_plan_id) && update) {
You already have all values in `initialValues`. No need to access internal form values.

```suggestion
 	const { update, initialValues } = this.props
    if (this.isEmptyFrequencyPlan(initialValues.frequency_plan_id) && update) {
      this.setState({
        showFrequencyPlanWarning: true,
      })
    }
```

Do we actually need this? Isnt it enough to check for empty `frequency_plan_id` in `construtor`?

2020-11-04 12:37 UTC, bafonins commented on pkg/webui/console/views/gateway-add/index.js
> +              formRef={React.createRef()}
What is the purpose of passing ref as a prop without actually using it in `<GatewayAdd />`?

2020-12-02 21:48 UTC, bafonins commented
@mjamescompton What is the status here?

2020-12-20 15:51 UTC, bafonins commented
@mjamescompton

2020-12-31 11:39 UTC, bafonins approved these changes

2021-01-04 10:26 UTC, kschiffer approved these changes

2021-01-06 10:22 UTC, merged