Add CLI command for sending end device uplinks
TheThingsNetwork/lorawan-stack pull request #3472
Opened 2020-11-12 13:30 UTC by neoaggelos

#### Summary

Closes #3144 

#### Changes

- Add a new `ttn-lw-cli end-devices simulate-uplink` command, accepting arguments for the uplink message.

#### Testing

- `ttn-lw-cli login`
- `ttn-lw-cli end-devices simulate-uplink app-id dev-id --uplink-message.f-port 13 --uplink-message.frm-payload 01010202`
- Uplink message is received from the Application Server, events are sent, integrations are working as they should.

##### Regressions

There should not be any.

#### Notes for Reviewers

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-11-12 15:07 UTC, johanstokking reviewed
We already have a top-level `simulate` command which can be confusing with this one.

2020-11-12 15:19 UTC, johanstokking requested changes

2020-11-12 15:19 UTC, johanstokking commented on cmd/ttn-lw-cli/commands/end_devices.go
> +			// fport, _ := cmd.Flags().GetUint32("f-port")
Remove

2020-11-12 15:19 UTC, johanstokking commented on cmd/ttn-lw-cli/commands/end_devices.go
> +			up.EndDeviceIdentifiers = *devID
This looks obsolete

2020-11-12 15:19 UTC, johanstokking commented on cmd/ttn-lw-cli/commands/end_devices.go
> +				EndDeviceIdentifiers: *devID,
With this

2020-11-12 15:19 UTC, johanstokking commented on cmd/ttn-lw-cli/commands/end_devices.go
> +				Simulated:            true,
Is this necessary when calling `SimulateUplink()`?

2020-11-12 15:19 UTC, johanstokking commented on cmd/ttn-lw-cli/commands/end_devices.go
> +	applicationUplinkFlags   = util.FieldFlags(&ttnpb.ApplicationUplink{}, "uplink_message")
Can we collapse this, so that it becomes `--frm-payload` ?

2020-11-18 15:26 UTC, htdvisser reviewed
Nothing to add to @johanstokking's review.

2020-12-08 08:43 UTC, johanstokking approved these changes

2020-12-08 10:46 UTC, rvolosatovs commented
Why not put this under `simulate application-uplink` or something similar?
We already have `ttn-lw-cli simulate` namespace and we have `ttn-lw-cli simulate uplink` as well. The suggested naming scheme is extremely confusing

2020-12-08 10:56 UTC, neoaggelos commented
> We already have a top-level simulate command which can be confusing with this one.

> Why not put this under simulate application-uplink or something similar?

The existing `ttn-lw-cli simulate` command is hidden, marked expiremental and largely undocumented, hence why I avoided using it.

2020-12-08 12:09 UTC, htdvisser commented
@rvolosatovs makes a good point. I think we can make this one `simulate application-uplink` and maybe even rename the other one to `simulate gateway-uplink` (it's experimental and hidden, no compatibility expected there).

2020-12-11 08:44 UTC, htdvisser commented on CHANGELOG.md
> +- Renamed expiremental command `ttn-lw-cli simulate uplink` to `ttn-lw-cli simulate gateway-uplink`.
"experimental" instead of "expiremental"

2020-12-11 08:44 UTC, htdvisser commented on cmd/ttn-lw-cli/commands/simulate.go
> +		Use:    "join-request",
1. Maybe this should also have the `gateway-` prefix
2. I think the description should be more clear about the fact that this "simulates a join request from an end device, sent through a simulated gateway connection"

2020-12-11 08:44 UTC, htdvisser commented on cmd/ttn-lw-cli/commands/simulate.go
> +		Short:  "Simulate a gateway uplink message (EXPERIMENTAL)",
I think the description should be more clear about the fact that this "simulates an uplink message from an end device, sent through a simulated gateway connection". I think "gateway uplink message" alone is not clear enough.

2020-12-11 08:44 UTC, htdvisser commented on cmd/ttn-lw-cli/commands/simulate.go
> +		Short: "Simulate application uplink message from an end device",
I think the description should be more clear about the fact that this "simulates an application-layer uplink message from an end device, sent directly to the application server"

2020-12-20 23:48 UTC, merged