Fix nested side navigation focus
TheThingsNetwork/lorawan-stack pull request #3560
Opened 2020-12-03 16:35 UTC by asmulko

#### Summary
Closes #3551

#### Changes

- `tabIndex` is set to` -1` on nested items when the dropdown is collapsed

#### Testing

Manually tested

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-12-03 18:20 UTC, kschiffer commented
Sorry, but after going through the diff, it became apparent to me that the solution suggested in #3551 using `tabindex` is actually not the correct solution for this. Instead, we should use simple styling to achieve the desired effect:

```diff
diff --git a/pkg/webui/components/navigation/side/list/list.styl b/pkg/webui/components/navigation/side/list/list.styl
index effe245e6..8b850437b 100644
--- a/pkg/webui/components/navigation/side/list/list.styl
+++ b/pkg/webui/components/navigation/side/list/list.styl
@@ -29,6 +29,10 @@
 
   &-nested > li
     height: 0
+    transition: visibility $ad.m, height $ad.m ease-in-out
+
+  &-nested:not(.list-expanded) > li
+    visibility: hidden
 
   &-expanded > li
     height: 3.1rem
```

Using `visibility` we can prevent the item from becoming focused (since invisible elements cannot be focused) while being able to preserve the animation.

2020-12-03 18:21 UTC, kschiffer requested changes
See my comment above.

2020-12-06 08:57 UTC, asmulko commented
> Sorry, but after going through the diff, it became apparent to me that the solution suggested in #3551 using `tabindex` is actually not the correct solution for this. Instead, we should use simple styling to achieve the desired effect:
> 
> ```diff
> diff --git a/pkg/webui/components/navigation/side/list/list.styl b/pkg/webui/components/navigation/side/list/list.styl
> index effe245e6..8b850437b 100644
> --- a/pkg/webui/components/navigation/side/list/list.styl
> +++ b/pkg/webui/components/navigation/side/list/list.styl
> @@ -29,6 +29,10 @@
>  
>    &-nested > li
>      height: 0
> +    transition: visibility $ad.m, height $ad.m ease-in-out
> +
> +  &-nested:not(.list-expanded) > li
> +    visibility: hidden
>  
>    &-expanded > li
>      height: 3.1rem
> ```
> 
> Using `visibility` we can prevent the item from becoming focused (since invisible elements cannot be focused) while being able to preserve the animation (which wouldn't be possible with `display: none`).

Agreed, looks way cleaner than the `tabIndex` solution I've implemented. Thank you!

2020-12-07 10:33 UTC, kschiffer approved these changes

2020-12-07 10:54 UTC, merged