Remove linking references
TheThingsNetwork/lorawan-stack pull request #3614
Opened 2020-12-23 08:27 UTC by asmulko

#### Summary

Closes #3542 

#### Changes

- Removed linking from create application 
- Removed linking from side menu
- Removed linking info from application overview
- Updated uplink/downlink not to depend on linking

Before:
![before_1](https://user-images.githubusercontent.com/72162194/102975592-ffe22e00-4508-11eb-9a05-7cf9d95983e6.png)
After: 
![after_1](https://user-images.githubusercontent.com/72162194/102975147-46835880-4508-11eb-894a-9e4a7d9af1d8.png)

Before:
![before_2](https://user-images.githubusercontent.com/72162194/102975594-01135b00-4509-11eb-8455-6c723393c34c.png)
After:
![after_2](https://user-images.githubusercontent.com/72162194/102975154-47b48580-4508-11eb-9670-99f1a917dd39.png)

Before:
![before_3](https://user-images.githubusercontent.com/72162194/102975602-02448800-4509-11eb-9d7f-ac36e8b53236.png)
After:
![after_3](https://user-images.githubusercontent.com/72162194/102975160-497e4900-4508-11eb-9425-64b8007acc9f.png)

#### Testing

Manually tested

#### Notes for Reviewers

- I would appreciate if someone could test this locally to see if nothing is broken, I could've missed something

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-12-24 13:04 UTC, bafonins requested changes

2020-12-24 13:04 UTC, bafonins commented on pkg/webui/console/containers/application-title-section/application-title-section.js
> -import ApplicationStatus from './status'
You can then also remove the `status` folder. Or can we still fetch up/down counts and last received timestamp from `ApplicationLinkStats` ? cc @adriansmares

2020-12-24 13:04 UTC, bafonins commented on pkg/webui/console/containers/application-title-section/application-title-section.js
> -  linkStats: PropTypes.applicationLinkStats,
You can also edit the `applicationLink` and `applicationLinkStats` prop-type definitions to match the current types.

2020-12-24 13:04 UTC, bafonins commented on pkg/webui/console/containers/application-title-section/application-title-section.js
> -  linkStats: PropTypes.applicationLinkStats,
`ApplicationLink` does not require `network_server_address` and `api_key` as those will be deprecated in v3.11

2020-12-24 13:41 UTC, adriansmares commented on pkg/webui/console/containers/application-title-section/application-title-section.js
> -import ApplicationStatus from './status'
`ApplicationLinkStats` is deprecated. There are no plans in bringing it back at the moment.

2020-12-28 09:54 UTC, adriansmares reviewed
I've tested it locally and works as expected. Test procedure:

- Create application
- Create end device
- Set application uplink payload formatters to the default JS formatter
- Send simulated uplink and check uplink contents (contains correct `decoded_payload`)

2020-12-28 16:27 UTC, bafonins approved these changes

2020-12-29 09:33 UTC, merged