Add create-admin-api-key is-db command
TheThingsNetwork/lorawan-stack pull request #3622
Opened 2020-12-28 14:07 UTC by pgalic96

#### Summary

Closes #3518 

#### Changes

- Move `io` internal package outside of `ttn-lw-cli` scope so it can be accessed by `ttn-lw-stack`
- Add `create-admin-api-key` that creates an API key with full rights on specified `id`
- Add `output-format` config parameter for `ttn-lw-stack`

#### Testing

- manual

##### Regressions

Possible regressions due to errors in renaming imports in `ttn-lw-cli`, tested by executing a subset of changed `ttn-lw-cli` commands

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2020-12-28 14:41 UTC, johanstokking approved these changes

2020-12-28 14:41 UTC, johanstokking commented on cmd/ttn-lw-stack/commands/config.go
> +	OutputFormat: "json",
Put this in a new section (via empty line) to reduce diff and internal merge friendliness

2020-12-28 14:41 UTC, johanstokking commented on pkg/identityserver/api_key_utils.go
> +func GenerateAPIKey(ctx context.Context, name string, rights ...ttnpb.Right) (key *ttnpb.APIKey, token string, err error) {
Needs godoc if it's exposed

2020-12-28 15:06 UTC, htdvisser requested changes

2020-12-28 15:06 UTC, htdvisser commented on CHANGELOG.md
> +- `ttn-lw-stack` CLI command for creating an API Key with full rights on a user.
Empty line between h3 and ul

2020-12-28 15:06 UTC, htdvisser commented on cmd/ttn-lw-stack/commands/is_db_create_api_key.go
> +		Use:   "create-admin-api-key",
I'd call this `create-user-api-key`, because this isn't limited to only admins.

2020-12-28 15:06 UTC, htdvisser commented on cmd/ttn-lw-stack/commands/is_db_create_api_key.go
> +	createAPIKeyCommand.Flags().String("id", "admin", "User ID")
The `--id` flag is confusing here, better to use `--user-id`

2020-12-29 08:39 UTC, htdvisser approved these changes

2020-12-29 18:11 UTC, merged