Update email templates
TheThingsNetwork/lorawan-stack pull request #3678
Opened 2021-01-19 10:47 UTC by htdvisser

#### Summary

This pull requests updates our email templates to make the web UI (the Console) the primary entrypoint for user actions instead of the CLI.

Closes #3674

#### Testing

Run The Things Stack, perform actions that trigger emails.

```
Hello,

You have been invited to join The Things Stack for LoRaWAN.

You can now go to http://localhost:1885/oauth/register?invitation_token=6UCDXBY4VXE5XEWK3X5VTQI6KV4DC4CHYIWIG4654YW4MEBRHFZA to register your user.

If you prefer to use the command-line interface, you can add "--invitation-token 6UCDXBY4VXE5XEWK3X5VTQI6KV4DC4CHYIWIG4654YW4MEBRHFZA" when running the "ttn-lw-cli users create" command.

Your invitation expires a week from now.
```

```
Dear admin,

User "hylke" wants to join The Things Stack for LoRaWAN.

You can go to http://localhost:1885/console/admin/user-management/hylke to view and approve (or reject) the user.

If you prefer to use the command-line interface, you can run the following command:

ttn-lw-cli users set hylke --state APPROVED (or --state REJECTED)
```

```

```
Please confirm your email address for The Things Stack for LoRaWAN.

Your email address will be used as contact for user "hylke".

You can go to http://localhost:1885/oauth/validate?reference=RKKD2IY2GYBEGBAJ63VPDWLSINY2CDHFZFMROPY&token=MKAP6ICOWZIRA52OE43TCE7OEUK6QCZDZ4VEEEZRZ3CJYD5AHFGQ to confirm your email address.

If you prefer to use the command-line interface, you can run the following command:

ttn-lw-cli users contact-info validate RKKD2IY2GYBEGBAJ63VPDWLSINY2CDHFZFMROPY MKAP6ICOWZIRA52OE43TCE7OEUK6QCZDZ4VEEEZRZ3CJYD5AHFGQ

These confirmation links expire 2 days from now.
```

```
Dear Hylke,

Your user "hylke" on The Things Stack for LoRaWAN is now approved.
```

Note that this same ☝️ email template is also used when OAuth clients are approved. We may want to add some if/else blocks to tell users that they can visit the console at `{{.Network.ConsoleURL}}`, but that may get a bit messy.

```
Dear Hylke,

A temporary password was requested for your user "hylke" on The Things Stack for LoRaWAN.

You can now go to http://localhost:1885/oauth/update-password?user=hylke&current=BNT7NOZ3URKLMTHTH5UG4NGL2RVDJHG2CKDLVZCDVVQVISG7NNRA to change your password.

If you prefer to use the command-line interface, you can run the following command:

ttn-lw-cli users update-password --user-id hylke --old BNT7NOZ3URKLMTHTH5UG4NGL2RVDJHG2CKDLVZCDVVQVISG7NNRA (add --revoke-all-access if you want to logout everywhere)

Your temporary password expires an hour from now.
```

```
Dear Admin,

A new API key "BKP5TVJLVUBPNVC6TBYQC4QRNYZQUBNXBQ4QLAI (Demo)" has been created for application "admin-app" on The Things Stack for LoRaWAN with the following rights:

RIGHT_APPLICATION_DEVICES_READ
RIGHT_APPLICATION_DEVICES_READ_KEYS
RIGHT_APPLICATION_DEVICES_WRITE
RIGHT_APPLICATION_DEVICES_WRITE_KEYS
RIGHT_APPLICATION_INFO
RIGHT_APPLICATION_SETTINGS_BASIC
RIGHT_APPLICATION_SETTINGS_PACKAGES
RIGHT_APPLICATION_TRAFFIC_READ

You can go to http://localhost:1885/console/applications/admin-app/api-keys/BKP5TVJLVUBPNVC6TBYQC4QRNYZQUBNXBQ4QLAI to view and edit this API key in the Console.

If you prefer to use the command-line interface, you can run the following commands to view or edit this API key:

ttn-lw-cli applications api-keys get --application-id admin-app --api-key-id BKP5TVJLVUBPNVC6TBYQC4QRNYZQUBNXBQ4QLAI
ttn-lw-cli applications api-keys set --application-id admin-app --api-key-id BKP5TVJLVUBPNVC6TBYQC4QRNYZQUBNXBQ4QLAI
```

```
Dear Admin,

The collaborator "hylke" of application "admin-app" on The Things Stack for LoRaWAN now has the following rights:

RIGHT_APPLICATION_ALL

You can go to http://localhost:1885/console/applications/admin-app/collaborators/user/hylke to view and edit this collaborator in the Console.

If you prefer to use the command-line interface, you can run the following commands to view or edit this collaborator:

ttn-lw-cli applications collaborators get --application-id admin-app --user-id hylke
ttn-lw-cli applications collaborators set --application-id admin-app --user-id hylke
```

##### Regressions

Unless I skipped an email during testing, I'm pretty sure that we're not trying to render undefined variables.

#### Notes for Reviewers

The `api-keys get` and `collaborators get` commands didn't exist in the CLI, I'm adding those in a separate pull request.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
	- [ ] Will open a documentation PR to describe the changed template variables
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-01-19 16:15 UTC, kschiffer requested changes
Am I missing it or is there actually no email sent to inform users that their accounts were approved?

2021-01-19 16:15 UTC, kschiffer commented on pkg/identityserver/emails/api_key_changed.go
>  {{$right}} {{end}}
Can we (additionally) pretty print this as well?

2021-01-19 16:15 UTC, kschiffer commented on pkg/identityserver/emails/api_key_changed.go
> +If you prefer to use the command-line interface, you can run the following commands to view or edit this API key:
I suggest referencing the CLI guide in the docs whenever we reference the CLI

https://www.thethingsindustries.com/docs/getting-started/cli/

2021-01-19 16:15 UTC, kschiffer commented on pkg/identityserver/emails/api_key_changed.go
> +ttn-lw-cli {{.Entity.Type}}s api-keys set --{{.Entity.Type}}-id {{.Entity.ID}} --api-key-id {{.Key.ID}}
```suggestion
ttn-lw-cli {{.Entity.Type}}s api-keys set --{{.Entity.Type}}-id {{.Entity.ID}} --api-key-id {{.Key.ID}}

For more information on how to use the command-line Interface (CLI) please refer to our documentation:
{{ .DocumentationUrl }}/getting-started/cli/
```

e.g. like this

2021-01-19 16:15 UTC, kschiffer commented on pkg/identityserver/emails/invitation.go
> +You can now go to {{ .Network.IdentityServerURL }}/register?invitation_token={{ .InvitationToken }} to register your user.
```suggestion
You can now go to {{ .Network.IdentityServerURL }}/register?invitation_token={{ .InvitationToken }} to register your user.

After successful registration, you can access the Console here: {{ .ConsoleURL }}
```

Let's make it more clear by also referencing the console here (which is very likely what the user will be interested in after registration).

2021-01-20 08:33 UTC, htdvisser commented on pkg/identityserver/emails/api_key_changed.go
>  {{$right}} {{end}}
That wourld require some refactoring to make the i18n package available to email templates. I'd rather do such refactoring in a separate PR and keep this one focused on the content itself.

2021-01-20 09:48 UTC, kschiffer approved these changes

2021-01-20 10:26 UTC, merged