Add gateway location tests
TheThingsNetwork/lorawan-stack pull request #3681
Opened 2021-01-20 11:32 UTC by asmulko

#### Summary

References #3606 

#### Changes

- Added gateway location e2e tests
- Added gateway location smoke test

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-02-01 10:33 UTC, kschiffer requested changes
Can you add a test that checks whether the location can be set by clicking into the map? This should be possible by selecting the map widget and using the `.click()` method. Note that you can [use this method with coordinates](https://docs.cypress.io/api/commands/click.html#Syntax).

2021-02-01 10:33 UTC, kschiffer commented on cypress/integration/console/gateways/location/create.spec.js
> +  })
There's no reason to assume that the location will have changed as a result of the submit, so these checks can be removed.

2021-02-01 10:33 UTC, kschiffer commented on cypress/integration/console/gateways/location/edit.spec.js
> +    )
```suggestion
```

2021-02-08 13:13 UTC, asmulko commented
> Can you add a test that checks whether the location can be set by clicking into the map? This should be possible by selecting the map widget and using the `.click()` method. Note that you can [use this method with coordinates](https://docs.cypress.io/api/commands/click.html#Syntax).

Thanks for the information on how to do it, I've added the test

2021-02-08 15:43 UTC, kschiffer approved these changes

2021-02-09 08:43 UTC, merged