Add device repository to the Console
TheThingsNetwork/lorawan-stack pull request #3695
Opened 2021-01-21 16:49 UTC by bafonins

#### Summary

References https://github.com/TheThingsNetwork/lorawan-stack/issues/3433

#### Changes

- Add dr service to JS SDK
- Add new end device creation form
- Add e2e for device creation from device repo
- Add `placeholder` prop to `<Select />`

#### Testing

...

##### Regressions

...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-01-21 21:12 UTC, kschiffer requested changes
Very nice!

Tested and works as expected.

One small UX thing: It should be so that when using keyboard to input and selecting one item inside `<Select />`, it should move the focus automatically to the next `<Select />`.

Please also see my remarks in the code. 

Note that none of these things are critical, so, considering the tight release-schedule, I leave it to your discretion which ones you want to address in for the release and which ones are to be fixed separately later-on.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/containers/fetch-select/index.js
> +      options: optionsFormatter(optionsSelector(state)),
`additionalOptions` is still used in `/containers/freq-plans-select/index.js`

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/device-add.styl
> +  margin-bottom: $ls.s
Please also add a bottom line here, like we do e.g. for the tabs within device payload formatters.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/manual/connect.js
> +// Copyright © 2020 The Things Network Foundation, The Things Industries B.V.
```suggestion
// Copyright © 2021 The Things Network Foundation, The Things Industries B.V.
```

nit

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-registration/freq-plans-select/index.js
> +          return []
```suggestion
          return plans
```

I guess a better option is to allow all plans then.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-registration/index.js
> +  fetching: 'Fetching template',
```suggestion
  fetching: 'Fetching template…',
```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-selection/brand-select/brand-select.js
> +      noOptionsMessage={handleNoOptions}
```suggestion
      noOptionsMessage={m.noOptionsMessage}
```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-selection/brand-select/connect.js
> +}
```suggestion
const mapStateToProps = (state, props) => ({
  appId: selectSelectedApplicationId(state),
  brands: selectDeviceBrands(state),
  error: selectDeviceBrandsError(state),
  fetching: selectDeviceBrandsFetching(state),
})
```

nit

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-selection/hw-version-select/hw-version-select.js
> +  }, [handleChange, options])
Maybe worth refactoring those into utility hooks, given that they are used identically throughout the DR select components.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-selection/index.js
> +          className={classnames(style.select, style.selectS)}
```suggestion
          inputWidth="s"
```

Please check whether you can achieve same results with the built in sizes.

```
PropTypes.inputWidth = PropTypes.oneOf(['xxs', 'xs', 's', 'm', 'l', 'full'])
```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/hints/other-hint.js
> +  manualLinkPath: '/tba',
```suggestion
  manualLinkPath: '/devices/adding-devices',
```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/hints/progress-hint.js
> +    'Cannot find your exact end device? <SupportLink>Get help here</SupportLink> and <ManualLink>try manual device registration</ManualLink>.',
@benolayinka please note that we need a doc page which helps users out when they have they have a device that is not (yet) part of the DR.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/repository.styl
> +      flex-basis: $fiw.s
```suggestion
```
These are already part of the input styles.

`<Select inputWidth="xs" />`
`<Select inputWidth="s" />`

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/repository.styl
> +        flex-basis: auto
idem
```suggestion

```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/hints/other-hint.js
> +    "We're sorry, but your device is not yet part of The Things Device Repository. You can use <ManualLink>manual device registration</ManualLink>, using the information your end device manufacturer
```suggestion
    "We're sorry, but your device is not yet part of The Things Device Repository. You can use <ManualLink>manual device registration</ManualLink>, using the information your end device manufacturer provided e.g. in the product's data sheet. Please also refer to hour documentation on <GuideLink>Adding Devices</GuideLink>.",
```

Sorry, this needs to reword a little (in deviation of the wireframe wording).

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-registration/index.js
> +      <Spinner center>
```suggestion
      <Spinner center after={0}>
```

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/device-registration/index.js
> +    <div>
nit: I think it would be better to use `<Overlay />` here, when the form is updated, to avoid the layout jumps when changing e.g. the `Profile (Region)`.

2021-01-21 21:12 UTC, kschiffer commented on pkg/webui/console/views/device-add/repository/hints/other-hint.js
> +    </div>
```suggestion
    <Notification
      info
      small
      className={style.container}
      title={m.hintTitle}
      content={m.hintMessage}
      messageValues={{
        ManualLink: msg => (
          <Link secondary key="manual-link" to={manualLinkPath}>
            {msg}
          </Link>
        ),
        GuideLink: msg => (
          <Link.DocLink secondary key="manual-guide-link" path={manualGuideDocsPath}>
            {msg}
          </Link.DocLink>
        ),
      }}
    />
```

This was meant as notification. Should've made that clearer.

2021-01-21 22:52 UTC, bafonins commented on pkg/webui/console/views/device-add/repository/device-selection/index.js
> +          className={classnames(style.select, style.selectS)}
Unfortunately setting `inputWidth` on inputs doesnt work here. I decided to set width here so I dont have do spend time on adjusting field styles and possibly breaking styling in other forms. However, I do agree that `inputWidth` should be used in this case.

2021-01-22 08:34 UTC, bafonins commented on pkg/webui/console/views/device-add/repository/device-selection/brand-select/brand-select.js
> +      noOptionsMessage={handleNoOptions}
See `noOptionsMessage` in https://react-select.com/props

2021-01-22 08:35 UTC, bafonins commented on pkg/webui/console/views/device-add/repository/device-registration/index.js
> +    <div>
Added. With this, `<Overlay />` is shown when refetching templates and no layout jumps.
<img width="790" alt="Screenshot 2021-01-22 at 10 31 01" src="https://user-images.githubusercontent.com/16374166/105466468-ee717a80-5c9c-11eb-8c95-4f447c0aaf7f.png">

2021-01-22 08:59 UTC, kschiffer approved these changes
Thank you

2021-01-22 10:06 UTC, neoaggelos approved these changes
Tested and working. One minor comment.

The field for AppKey hides the last byte. Example, for AppKey `001122334455667788AABBCCDDEEFF00`

![image](https://user-images.githubusercontent.com/1888650/105477044-07345d00-5caa-11eb-8a63-132c47050d4f.png)

![image](https://user-images.githubusercontent.com/1888650/105477093-17e4d300-5caa-11eb-9b10-0425af88b49f.png)

2021-01-22 10:55 UTC, johanstokking commented
@bafonins I'm getting an error when running locally, after `tools/bin/mage js:build`:

```
index.js:215 Uncaught TypeError: Cannot read property 'listBrands' of undefined
    at Object../pkg/webui/console/api/index.js (index.js:215)
    at r (bootstrap:63)
    at Object../pkg/webui/console/store/middleware/logics/index.js (console.bc26ac8ebea398a7bfa2.js:187)
    at r (bootstrap:63)
    at Object.<anonymous> (console.bc26ac8ebea398a7bfa2.js:187)
    at Object../pkg/webui/console/store/index.js (console.bc26ac8ebea398a7bfa2.js:187)
    at r (bootstrap:63)
    at Module../pkg/webui/console.js (console.bc26ac8ebea398a7bfa2.js:187)
    at r (bootstrap:63)
    at Object.0 (console.bc26ac8ebea398a7bfa2.js:187)
```

Frontend assets seem to be up-to-date; `/account` works.

2021-01-22 10:58 UTC, kschiffer commented
Make sure it's rebased on [#3543](https://github.com/TheThingsNetwork/lorawan-stack/pull/3543) and run `mage js:clean jsSdk:clean js:build`.

2021-01-22 11:44 UTC, johanstokking approved these changes

2021-01-22 12:11 UTC, merged