Soft-Deleted Entity Handling
TheThingsNetwork/lorawan-stack pull request #3739
Opened 2021-02-04 12:47 UTC by htdvisser

#### Summary

This PR improves handling of soft-deleted entities in the Identity Server.

Refs #604 
Closes #1903 
Closes #1121

#### Changes

- API: Add `deleted_at` field to API of entities that can be soft-deleted
- API: Add `include_deleted` to `List` and `Search` RPCs in registries with soft-delete
- API: Add `Restore` RPCs to registries with soft-delete
	- This requires the DELETE right, meaning that anyone who can delete the application, can also restore it.
- API: Add missing `Purge` RPC to OAuth client registry
- CONF: Add "restore window" config option that sets how long after deleting an entity it can still be restored.
- IS: Implement listing deleted entities
- IS: Implement searching for deleted entities
- IS: Implement restoring deleted entities
- IS: Implement missing `Purge` RPC of OAuth client registry
- Console: Implement listing / searching for deleted entities

#### Testing

- Unit tests
- CLI
- Console (in progress)

##### Regressions

...

#### Notes for Reviewers

There's still some work to do:

- [ ] Make the checkbox render nicely in the Console
	- This was a very quick change without input from @kschiffer about UI/UX. He should probably go over that.
- [ ] Add Restore functionality to the Console
	- This could also use some UI/UX design from @kschiffer.
- [ ] Add RPCs for listing soft-deleted entities for which the cooldown window has expired (meaning that users are no longer allowed to restore them).
	- The initial implementation will probably use cluster auth for this. No idea what we can do for external integrations, but I think that's out of scope here anyway.
- [ ] Changelog
- [ ] Documentation

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-02-05 13:34 UTC, kschiffer commented
UX wise, this should ideally work like this:

*   We should use the trash metaphor and add a "Trash" tab to the entity tables
*   In the "Trash" tab, every table row should have two buttons "Restore" and "Permanently delete"
*   The "Trash" tab should have a "Empty trash" button to quickly purge all items
*   The confirmation toast for entity deletions needs an "Undo" button
*   The confirmation modal needs to be updated to remove "This action cannot be undone!" warnings

This is quite some changes which I would recommend doing in a separate PR. Maybe it's best to limit this PR to backend changes only? I can then take your Console work as foundation for a follow-up PR.

2021-02-05 14:18 UTC, kschiffer requested changes
Codeowned files LGTM. See my remark on the Console bit.

2021-02-05 14:18 UTC, kschiffer commented on pkg/identityserver/organization_registry.go
> +		}
This appears like an unnecessary limitation to me. Why shouldn't it be possible to restore the entity until it is actually GC'ed? (Idem for the other entity's restore methods)

2021-02-05 14:18 UTC, kschiffer commented on pkg/identityserver/application_registry.go
> +	}
With regards to the UX that I outlined above, what would be needed is actually an exclusive filter. Something like `IsDeleted` which then only gets deleted or not deleted records.

2021-02-08 12:34 UTC, htdvisser commented
I've updated the PR according to @kschiffer's suggestions. The API now takes a `deleted` parameter that makes the IS only return deleted entities if true. The Console changes have been taken out of this PR.

> @kschiffer:
> This appears like an unnecessary limitation to me. Why shouldn't it be possible to restore the entity until it is actually GC'ed? (Idem for the other entity's restore methods)

The reason here is external services. The idea is that those will periodically ask the IS about deleted (and unrecoverable) entities, so that those services can also purge their databases. This means that we should allow for some time between entities being unrecoverable, and being really gone.

2021-02-08 13:01 UTC, kschiffer approved these changes
Changes LGTM, haven't tested CLI.

2021-02-10 12:12 UTC, johanstokking reviewed
API LGTM

2021-02-17 13:56 UTC, johanstokking approved these changes
API LGTM now with a green button

2021-02-17 14:01 UTC, rvolosatovs approved these changes

2021-02-17 14:53 UTC, merged