Add auto width prop for byte field
TheThingsNetwork/lorawan-stack pull request #3792
Opened 2021-02-12 15:25 UTC by asmulko

#### Summary

Closes #3784

#### Changes

- added `autoWidth` prop to field component
- updated mixins
- apply width based on byte `max` prop if `autoWidth = true`

#### Testing

Manually tested

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-02-15 11:02 UTC, bafonins commented
IMO, this doesnt look right.

![field](https://user-images.githubusercontent.com/16374166/107938359-f071e500-6f8d-11eb-94e8-2ec83998d769.png)

Can we use `inputWidth` prop to increase input width for 16byte long inputs?

2021-02-15 12:27 UTC, kschiffer requested changes
- Instead of using the new `autoWidth` prop, let's adjust the styling for `inputWidth="auto"` for `<Input.Byte />` components.
- Let's then also adjust the default value for `inputWidth` to "auto" (for `<Input.Byte />`).
- There shouldn't be any changes to `<Form.Field />` necessary
- It appears like the auto width calculation needs to be adjusted to the new spacing
In case of the `AppKey` input, since the PR adjusted the spacing of the byte values, it appears like we don't need to use autoWidth here because it looks better with the width aligned to the other fields, and it is possible now since it does not cover the last byte anymore.

2021-02-16 14:47 UTC, kschiffer requested changes
What about

> Let's then also adjust the default value for `inputWidth` to `"auto"` (for `<Input.Byte />`).

?

So we would make this default, except for the `AppKey` input, where we would overwrite the default (since it's sort of a special case). After you change the default value, make sure it does not break any layouts in our forms.

2021-02-16 14:47 UTC, kschiffer commented on pkg/webui/components/input/index.js
> +      if (max && (inputWidth === 'auto' || max > 16)) {
```suggestion
      if (max && (inputWidth === 'auto')) {
```

I don't think we need that, we should rather make sure that we set `inputWidth` actively.

2021-02-17 10:47 UTC, kschiffer requested changes
Looking good now, please make sure the auto width is also applied to the AppEUI field:
![image](https://user-images.githubusercontent.com/5710611/108193601-eed32900-7115-11eb-8ef8-3091c5d3deae.png)

2021-02-17 10:47 UTC, kschiffer commented on pkg/webui/components/input/index.js
> +    inputWidth: undefined,
Please add a comment that the default value is set programmatically based on input type.

2021-02-18 11:11 UTC, kschiffer approved these changes

2021-02-18 11:11 UTC, kschiffer commented on pkg/webui/components/input/index.js
> +        : null
```suggestion
    const passedProps = { 
      ...rest,
      ...(type === 'byte' ? { showPerChar } : {})
    }
```

And then pass that to the component.

2021-02-18 11:58 UTC, merged