Add Telemetry to PBA
TheThingsNetwork/lorawan-stack pull request #3835
Opened 2021-02-19 15:10 UTC by htdvisser

#### Summary

This PR adds Prometheus telemetry to the Packet Broker Agent.

#### Testing

⚠️ I haven't tested this. Was hoping that @johanstokking could do that.

##### Regressions

None expected. Worst case it just doesn't work.

#### Notes for Reviewers

⚠️ @johanstokking please test this

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-02-19 15:17 UTC, adriansmares approved these changes
This looks good to me (did not test).

I suggest moving observations to `observe*` functions, in case we think about adding events somewhere in the future.

2021-02-19 16:24 UTC, johanstokking requested changes
Will test, needs small fix though

2021-02-19 16:24 UTC, johanstokking commented on pkg/packetbrokeragent/agent.go
> +	homeNetworkNetID.UnmarshalNumber(up.ForwarderNetId)
```suggestion
	homeNetworkNetID.UnmarshalNumber(up.HomeNetworkNetId)
```

2021-02-19 16:31 UTC, johanstokking commented on pkg/packetbrokeragent/agent.go
> +	homeNetworkNetID.UnmarshalNumber(up.ForwarderNetId)
It's Friday, it's ok

2021-02-22 10:46 UTC, htdvisser commented
> I suggest moving observations to `observe*` functions, in case we think about adding events somewhere in the future.

I prefer to keep things simple until we actually decide to add those events.

2021-03-02 13:05 UTC, johanstokking approved these changes
Tested and works

2021-03-02 13:15 UTC, johanstokking commented
```
# HELP ttn_lw_pba_downlink_forwarded_total Total number of downlinks forwarded to Packet Broker
# TYPE ttn_lw_pba_downlink_forwarded_total counter
ttn_lw_pba_downlink_forwarded_total{forwarder_cluster_id="",forwarder_net_id="000000",forwarder_tenant_id="johan",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 1
# HELP ttn_lw_pba_downlink_received_total Total number of downlinks received from Packet Broker
# TYPE ttn_lw_pba_downlink_received_total counter
ttn_lw_pba_downlink_received_total{forwarder_cluster_id="",forwarder_net_id="000000",forwarder_tenant_id="johan",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 1
# HELP ttn_lw_pba_uplink_forwarded_total Total number of uplinks forwarded to Packet Broker
# TYPE ttn_lw_pba_uplink_forwarded_total counter
ttn_lw_pba_uplink_forwarded_total{forwarder_cluster_id="",forwarder_net_id="000000",forwarder_tenant_id="johan"} 1
# HELP ttn_lw_pba_uplink_received_total Total number of uplinks received from Packet Broker
# TYPE ttn_lw_pba_uplink_received_total counter
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="",forwarder_net_id="000000",forwarder_tenant_id="johan",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 1
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-eu1",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 21
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-au",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 87
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-brazil",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 6
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-eu-1",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 79
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-eu-2",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 34
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-eu-3",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 238
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-eu-4",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 385
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-switch",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 13
ttn_lw_pba_uplink_received_total{forwarder_cluster_id="ttn-v2-us-west",forwarder_net_id="000013",forwarder_tenant_id="ttn",home_network_cluster_id="johan-dev",home_network_net_id="000000",home_network_tenant_id="johan"} 92
```

2021-03-02 13:28 UTC, merged