Add application payload formatters e2e tests
TheThingsNetwork/lorawan-stack pull request #3841
Opened 2021-02-22 16:07 UTC by asmulko

#### Summary

References #3606 

#### Changes

- Added application payload formatters e2e tests

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-02-22 16:13 UTC, asmulko commented
Work in progress, I am going to add end devices payload formatters here as well

2021-02-25 11:19 UTC, kschiffer requested changes
Have some small remarks.

2021-02-25 11:19 UTC, kschiffer commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +      cy.clearCookies()
Is this really necessary? Cypress should clear cookies and localStorage between tests anyway.

[https://docs.cypress.io/api/commands/clearlocalstorage.html#Syntax](https://docs.cypress.io/api/commands/clearlocalstorage.html#Syntax)

https://docs.cypress.io/api/commands/clearcookies.html#Syntax

See also my comment below. I think we can remove this before hook altogether.

2021-02-25 11:19 UTC, kschiffer commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +      })
I think we should avoid these double logins. They only take time and don't provide any value. You could rather login and create the application/end device in these before hooks.

2021-02-25 11:19 UTC, kschiffer commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +        cy.findByTestId('code-editor').should('exist')
```suggestion
        cy.findByTestId('code-editor').should('be.visible')
```

2021-02-25 13:47 UTC, bafonins requested changes

2021-02-25 13:47 UTC, bafonins commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +      it('successfully changes formatter type to Javascript', () => {
```suggestion
      it('succeeds changing formatter type to Javascript', () => {
```

Please revisit our testing guidelines https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.11/DEVELOPMENT.md#javascript-based-tests

2021-03-03 09:31 UTC, bafonins requested changes
Please see my comments

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/organizations/edit.spec.js
> +  it('succeed editing organization name and description', () => {
```suggestion
  it('succeeds editing organization name and description', () => {
```

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/organizations/edit.spec.js
> +  it('succeed deleting organization', () => {
```suggestion
  it('succeeds deleting organization', () => {
```

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +        cy.loginConsole({ user_id: user.ids.user_id, password: user.password })
nit
```suggestion
        cy.loginConsole({ user_id: userId, password: user.password })
```

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +        cy.loginConsole({ user_id: user.ids.user_id, password: user.password })
nit
```suggestion
        cy.loginConsole({ user_id: userId, password: user.password })
```

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +        cy.loginConsole({ user_id: user.ids.user_id, password: user.password })
nit
```suggestion
        cy.loginConsole({ user_id: userId, password: user.password })
```

2021-03-03 09:31 UTC, bafonins commented on cypress/integration/console/shared/payload-formatters/edit.spec.js
> +        cy.loginConsole({ user_id: user.ids.user_id, password: user.password })
nit
```suggestion
        cy.loginConsole({ user_id: userId, password: user.password })
```

2021-03-03 09:31 UTC, bafonins commented on pkg/webui/console/containers/device-payload-formatters/downlink.js
> +  async onSubmitSuccess() {
Please remove `L96-L100` then. Currently, two toasts are shown on successful payload formatter update.

2021-03-03 09:31 UTC, bafonins commented on pkg/webui/console/containers/device-payload-formatters/downlink.js
> +  async onSubmitSuccess() {
You can use the uplink form as a reference

2021-03-05 12:51 UTC, bafonins approved these changes

2021-03-08 10:11 UTC, kschiffer approved these changes

2021-03-09 09:40 UTC, merged