Prevent UDP gateways log message floods
TheThingsNetwork/lorawan-stack pull request #3924
Opened 2021-03-16 00:57 UTC by neoaggelos

#### Summary

Closes #3839 

#### Changes

- Maintain an LFU cache with gateways where the rate limit has been exceeded.
- If error is of type Resource Exhausted, log the message if the gateway is not in the list of rate limited gateways.

#### Testing

Integration testing with UDP gateway

##### Regressions

There should not be any.

#### Notes for Reviewers

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-03-16 08:21 UTC, johanstokking reviewed
LGTM

Please revert the changes to `data/lorawan-devices`

2021-03-16 10:02 UTC, adriansmares approved these changes

2021-03-16 10:08 UTC, KrishnaIyer approved these changes

2021-03-16 10:08 UTC, KrishnaIyer commented on CHANGELOG.md
> +- Prevent flooding logs with "Packet Filtered" messages when UDP gateways exceed the maximum rate limit. Only one message per minute will be printed for each gateway.
Nit; Not sure this is a change that "users" care about. Maybe Enterprise customers.

2021-03-16 12:11 UTC, johanstokking requested changes
Revert changes of `lorawan-devices` submodule

2021-03-17 10:34 UTC, johanstokking approved these changes

2021-03-17 12:05 UTC, merged