Fix JsSDK field mask paths for setting end devices
TheThingsNetwork/lorawan-stack pull request #4086
Opened 2021-04-22 21:02 UTC by neoaggelos

#### Summary

Closes #4082 

#### Changes

- Generate the `device-entity-map.json` file dynamically from the allowed field mask paths by the API.
- Fix `mage jsSDK:deviceFieldMasks` target to generate the file when the field mask paths have changed.

#### Testing

- Rebuild console with the new `device-entity-map.json` definitions and verify that the Console does not ignore MAC settings and MAC state fields.
- CI
- End to end tests

##### Regressions

There should not be any, the allowed fields should be up to date since they are generated by the API.

#### Notes for Reviewers

@bafonins I am not very familiar with the JS SDK. Is there anything I might have missed?

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [X] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [X] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-04-22 22:01 UTC, neoaggelos commented
Converting to draft until the End to end tests failures are resolved.

2021-04-28 08:29 UTC, kschiffer requested changes
This appears to make problems when creating ABP devices via the device repository, which sets the MAC state directly. I don't have time to help you out with this now. @bafonins maybe?

2021-04-28 08:29 UTC, kschiffer commented on CHANGELOG.md
> +- Importing end devices from the Console would occasionaly ignore some device MAC settings fields.
```suggestion
- Importing end devices from the Console would occasionally ignore some device MAC settings fields.
```

2021-04-29 08:51 UTC, johanstokking approved these changes

2021-04-29 13:49 UTC, kschiffer approved these changes
LGTM

2021-04-30 04:23 UTC, merged