Update UI related dependencies
TheThingsNetwork/lorawan-stack pull request #4104
Opened 2021-04-29 20:01 UTC by asmulko

#### Summary

References #3934

#### Changes
- Updated UI related dependencies

#### Testing

- Manually tested

#### Notes for Reviewers

Based on #3787

Cherry-picked commits:
- 2bb8a6fada00a3a9e6789dfaf160ab714918d83e
- 6ac01fa475e5ed978e7571f5bae79cf568c29e9c
- 466863f13b6731dbbb5fea794d1dbabe520d5252

#### Checklist
- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-04-30 12:07 UTC, kschiffer requested changes
This PR has some eslint and prettier update related changes to the codebase which should need to be removed. Otherwise this looks good to me, but again this is somewhat of a self-review so @bafonins please also have a look.

2021-04-30 12:07 UTC, kschiffer commented on pkg/webui/account/store/actions/user.js
> +)
The changes that result from updating prettier should not be part of this PR, but rather be incorporated in the PR that updates prettier. This should fix itself when you rebase this on master after #4083 was merged.

2021-05-04 08:39 UTC, kschiffer approved these changes

2021-05-04 11:03 UTC, bafonins approved these changes

2021-05-04 17:47 UTC, merged