Add previews for events with google.protobuf.Value data
TheThingsNetwork/lorawan-stack pull request #4173
Opened 2021-05-12 13:43 UTC by htdvisser

#### Summary

This adds previews for event data of type `google.protobuf.Value`.

#### Testing

Locally. It looks like this:

<img width="1280" alt="Screen Shot 2021-05-12 at 15 37 33" src="https://user-images.githubusercontent.com/181308/117984294-ffbbc100-b337-11eb-956f-b1b0ea6bbbac.png">

Note the `["description"]` for the "Update gateway" event, and the `cluster` for the "Forward uplink message" event.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-05-12 14:46 UTC, kschiffer requested changes
Small tweaking necessary.

2021-05-12 14:46 UTC, kschiffer commented on pkg/webui/console/components/events/previews/value.js
> +  return <Message className={style.plainText} content={data.value} />
`<Message />` is only for i18n messages. To just show the plain value, you should use

```
<DescriptionList.Item key="data.value" data={data.value} />
```

Then make sure to wrap the whole output around `<DescriptionList.Item title={sharedMessages.value} />`

(also the JSON output should be wrapped around this)

2021-05-12 15:02 UTC, htdvisser commented
@kschiffer can you take over, or re-assign to someone else? I probably won't be able to finish this before the implementation deadline next week, and for you it's probably only a couple minutes work.

2021-05-17 09:36 UTC, kschiffer approved these changes

2021-05-17 09:37 UTC, kschiffer commented on pkg/webui/console/components/events/previews/value.js
> +  return <Message className={style.plainText} content={data.value} />
I eventually decided against using the `title={sharedMessages.value}`, since it can be confusing for some values.

2021-05-17 09:39 UTC, merged