Prevent users from submitting zero or empty security keys in the Console
TheThingsNetwork/lorawan-stack pull request #4543
Opened 2021-08-18 10:36 UTC by bafonins

#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/4539

<details>
<summary>Screenshots</summary>

<img width="708" alt="Screenshot 2021-08-18 at 13 37 47" src="https://user-images.githubusercontent.com/16374166/129883938-1ba9d2b1-5f61-4a82-90cd-f2966c0fd7b4.png">
<img width="708" alt="Screenshot 2021-08-18 at 13 37 37" src="https://user-images.githubusercontent.com/16374166/129883942-c06fe215-c6ce-4034-96c0-a117a8ff3b36.png">

</details>

#### Changes

- Move validation for form values to respective sections in the device general settings page.
- Fix and improve validation for session keys

#### Testing

manual

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-08-18 12:07 UTC, kschiffer requested changes

2021-08-18 12:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/network-server-form/index.js
> +        })
It's currently not possible to remove an existing key (by removing the value and submitting it as emtpy), since `diff()` will not include such keys.

2021-08-18 12:09 UTC, kschiffer commented
While testing, I saw that the AppSKey inside the application layer form needs the same fix wrt zero values.

2021-08-18 12:11 UTC, kschiffer commented
Also, just to make sure: Is it correct that `SNwkSIntKey` and `NwkSEncKey` should be removable? @johanstokking

2021-08-19 08:09 UTC, johanstokking commented
> Also, just to make sure: Is it correct that `SNwkSIntKey` and `NwkSEncKey` should be removable? @johanstokking

In LoRaWAN 1.0, they don't exist. In LoRaWAN 1.1, they do and are required.

2021-08-24 11:45 UTC, kschiffer requested changes
The `AppSKey` should also not allow zero values:
![image](https://user-images.githubusercontent.com/5710611/130610736-21e55a42-030e-4855-8a67-2b82fafcc066.png)

Otherwise LGTM

2021-08-24 13:00 UTC, kschiffer approved these changes

2021-08-24 13:13 UTC, merged