Feature/2831 non tls lns
TheThingsNetwork/lorawan-stack pull request #4604
Opened 2021-09-09 08:13 UTC by KrishnaIyer

#### Summary

Closes #2381 

#### Changes

- Add an optional schema support to the `gateway_server_address` regex.
- Update CUPS flow to skip credentials.
- (Try to) update the console regex.
- Remove some unused code that `go vet` was complaining about.

#### Testing

UT + local stack

##### Regressions

 We're just allowing extra characters to a string value so I don't think there's any.

#### Notes for Reviewers

@bafonins / @kschiffer : The changes I've made here to the console files don't seem to work. I've run the following
```
tools/bin/mage jsSDK:clean jsSDK:build js:clean js:build
```

<img width="523" alt="Screenshot 2021-09-09 at 09 53 01" src="https://user-images.githubusercontent.com/13186113/132647071-c8f8f1ff-70d3-47ed-8f3c-44da37a5add9.png">

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-09-09 12:11 UTC, kschiffer requested changes

2021-09-09 12:11 UTC, kschiffer commented on pkg/webui/console/components/gateway-data-form/validation-schema.js
> +import { address as addressWithOptionalScheme, delay as delayRegexp } from '@console/lib/regexp'
```suggestion
import { addressWithOptionalScheme as addressWithOptionalSchemeRegexp, delay as delayRegexp } from '@console/lib/regexp'
```

2021-09-09 12:11 UTC, kschiffer commented on pkg/webui/console/views/gateway-general-settings/basic-settings-form/validation-schema.js
> +import { id as gatewayIdRegexp, address as addressWithOptionalScheme } from '@console/lib/regexp'
```suggestion
import { id as gatewayIdRegexp, addressWithOptionalScheme as addressWithOptionalSchemeRegexp } from '@console/lib/regexp'
```

2021-09-09 12:11 UTC, kschiffer commented on pkg/webui/console/views/gateway-general-settings/basic-settings-form/validation-schema.js
> +    addressWithOptionalScheme,
```suggestion
    addressWithOptionalSchemeRegexp,
```

2021-09-09 12:11 UTC, kschiffer commented on pkg/webui/console/components/gateway-data-form/validation-schema.js
> +    addressWithOptionalScheme,
```suggestion
    addressWithOptionalSchemeRegexp,
```

2021-09-10 07:33 UTC, htdvisser commented on pkg/basicstation/cups/update_info.go
> +		if scheme != "ws" {
Shouldn't we just check for `wss` here? Otherwise we'd also run this if anyone decided to put `tcp://` for the scheme.

2021-09-13 13:38 UTC, htdvisser approved these changes
LGTM

2021-09-15 09:06 UTC, kschiffer approved these changes

2021-09-15 09:08 UTC, merged