Expand toggle sections with invalid fields
TheThingsNetwork/lorawan-stack pull request #4721
Opened 2021-10-07 15:00 UTC by kschiffer

#### Summary
Follow up from #4684, with added fixes and improvements. Many thanks to @brycechampaign for co-authoring this 👍!

Closes #4558.

#### Changes
- Remove HTML5 form validation form our forms (we use our own validation system)
- Make form sections aware of the form fields they render and automatically expand the section when it has an invalid field

#### Testing

Manual testing. See reproduction steps in #4558.

#### Notes for Reviewers
The HTML5 validation was previously preventing the submit logic from being fired when a field was deemed as invalid by the browser. E.g. when entering a `e` into a number field (this is possible because it can be used to enter exponents) and trying to submit. Instead of working around that, I concluded that we don't need the HTML5 validation since we have our own validation system in place which takes care of any input error anyway and does not trigger arbitrary side-effects such as blocking the `onSubmit` handler. This also streamlines the validation UX.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-10-12 07:41 UTC, bafonins requested changes

2021-10-12 07:41 UTC, bafonins commented on pkg/webui/components/form/section/index.js
> +    if (child && child.props && child.props.children) {
In this case recursion goes further than the `Field` component which must be the base case. Consider the following example:
```js
      <Form.Field
        component={Radio.Group}
      >
        <Radio />
        <Radio />
        <Radio />
      </Form.Field>
```
With current implementation `recursiveMap` also visits each `<Radio />` component which is not needed at all.

2021-10-12 07:41 UTC, bafonins commented on pkg/webui/components/form/section/index.js
> +      const fieldNames = recursiveMap(children, child => {
This is executed on every interaction with the form, however we are interested in form fields that failed validation only on submission.

2021-10-12 07:41 UTC, bafonins commented on pkg/webui/components/form/section/index.js
> +    return fn(child)
Do we really need recursion here?

2021-10-12 07:41 UTC, bafonins commented on pkg/webui/components/form/section/index.js
> +            setCollapsed(false)
The only reason why this works is because of [this](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.15/pkg/webui/console/views/device-add/manual/form/form.js#L359-L363). If you remove that part the section wont expand on validation errors.
This PR should replace [this check](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.15/pkg/webui/console/views/device-add/manual/form/form.js#L359-L363) and make sure that the form "knows" when to expand section components without explicitly specifying this for each field.

2021-10-12 07:41 UTC, bafonins commented on pkg/webui/components/form/section/index.js
> +        if (child !== null && child.type === Field && 'name' in child.props) {
```suggestion
        if (React.isValidElement(child) && child.type === Field) {
```

```js
React.isValidElement(null) // => false
```

2021-12-23 10:07 UTC, kschiffer commented
Closing this for now until we have capacity to work on this.

2021-12-23 10:07 UTC, closed without merging