console: Skip payload crypto ui, validation schema, initial values, u…
TheThingsNetwork/lorawan-stack pull request #4851
Opened 2021-11-09 16:54 UTC by ryaplots

…pdate app, e2e test

#### Summary

Referring to #4782
To create a skip payload crypto (radio buttons on the device general settings and checkbox on the application general settings)

#### Changes

- pkg/webui/console/views/device-general-settings/application-server-form/index.js: added the radio buttons and form validation with default values.
- pkg/webui/console/views/application-general-settings/index.js: added a checkbox, its initial value (/mapping.js) and validation schema
- pkg/webui/console/store/middleware/logics/applications.js: middleware logic for updating an application
- pkg/webui/console/store/actions/link.js: action for updating an application
- cypress/integration/console/applications/edit.spec.js: checkbox e2e test

#### Testing

Trying to set up the test env correctly (TO EDIT)

##### Regressions

Application updating, skip payload crypto. 

#### Notes for Reviewers

In the device general settings I am validating the payload crypto twice. I did it this way because:
- the payload crypto should be sent as a boolean (these are inferred from the chosen radio button) 
- radio buttons are part of the form and they don't accept boolean as value
- I need to set the initial value as default which would not be possible if the form was validated with only a boolean.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-11-10 15:30 UTC, kschiffer reviewed
Good start! See my remarks.

2021-11-10 15:30 UTC, kschiffer commented on pkg/webui/console/views/application-general-settings/index.js
> +    skip_payload_crypto: Yup.boolean().default(false),
```suggestion
    skip_payload_crypto: Yup.boolean(),
```

I don't think you need that.

2021-11-10 15:30 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +        component={RadioButton.Group}
Have a look into the `encode`/ `decode` props of the `<Form.Field />`. You can use that to marshal values from the backend shape to the frontend shape and vice versa. Iirc the backend expects either `true`, `false` or `null`. If you use a `decode` function you can convert this into `skip`, `include` and `default` and the other way around.

2021-11-10 15:30 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +    skip_payload_crypto_overrride: Yup.boolean().nullable().default(null),
You don't need to use two values here. You can use `decode` and `encode` props of the `<Form.Field />` to marshal between notations. See my other comment below. In the validation schema you should think about validating the values in a way that they can be sent straight to the backend.

2021-11-16 14:07 UTC, kschiffer requested changes
Looking good, but the cypress tests need some restructuring.

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +      cy.findByRole('checkbox').uncheck()
This will potentially generate a false positive / false negative when we add another checkbox input to the application form. You should use `findByLabelText()` rather.

Generally, when writing cypress tests, try to mimic the conscious action of the user. E.g. a user would not just click on a checkbox, they would scan for a text that is about skipping payload crypto and check the checkbox connected to it. Writing tests in this way makes them more sustainable even when we change the format or structure of the form.

See also our development guidelines [about end-to-end tests](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.16/DEVELOPMENT.md#guiding-principle) and the docs of [testing library](https://testing-library.com/docs/).

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +    it('combination skip payload crypto enabled/disabled on application level and default on device level', () => {
Make sure to [name and structure your tests correctly](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.16/DEVELOPMENT.md#structurizing-tests).

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +        .findByText(`Simulation is disabled for devices that skip payload crypto`)
```suggestion
        .findByText('Simulation is disabled for devices that skip payload crypto')
```

2021-11-16 14:07 UTC, kschiffer commented on pkg/webui/console/views/application-general-settings/index.js
> +            skip_payload_crypto: appValues.skip_payload_crypto,
```suggestion
```
Is this necessary? The new value should be part of `...changed` anyway (?)

2021-11-16 14:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +        encode={encodeSkipPayloadCrypto}
```suggestion
        horizontal
        encode={encodeSkipPayloadCrypto}
```

Better layout.

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +      cy.findByRole('button', { name: 'Save changes' }).click()
The functionality of the application general settings page is not relevant for this test. You should instead make the required API calls directly to achieve the modifications directly (and more quickly).
If you want to verify the integrity of a complete flow of actions of different domains, you should write a smoke test instead.

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +      )
You are mixing intercepting and actual modifications (like above). You should try to avoid API mocks as much as possible, since they lower the fidelity of the test. You can do an action POST request here as well to achieve the desired modifications in the registry.

2021-11-16 14:07 UTC, kschiffer commented on cypress/integration/console/devices/messaging/edit.spec.js
> +      cy.findByRole('button', { name: 'Simulate uplink' }).should('be.enabled')
Do not combine multiple distinct tests into one. If you do that, the other modifications done before could interfere with the test and lower its expressiveness. Try to chunk tests into distinct bits that test a single thing in isolation.

A good test setup would resemble sth like:

```js
describe('Uplink', () => {
  …
  describe('when application link skips payload crypto', () => {
    beforeEach(() => { … })
    it('disables messaging when not using a SPC overwrite', () => {})
    it('still allows messaging when device disabled SPC via overwrite', () => {})
  })
  describe('when application link doesn't skip payload crypto', () => {
    beforeEach(() => { … })
    it('enables messaging when not using a SPC overwrite', () => {})
    it('still disables messaging when device disabled SPC via overwrite', () => {})
  })
})
```

All of these above should use direct API calls to set up the application and end device for the test scenario and only then run the assertions.

2021-11-17 13:16 UTC, ryaplots commented on pkg/webui/console/views/application-general-settings/index.js
> +            skip_payload_crypto: appValues.skip_payload_crypto,
I think you are right and it is not necessary.

2021-11-22 11:04 UTC, kschiffer commented on pkg/webui/console/views/application-general-settings/index.js
> +      await updateApplicationLink(application_id, update)
You need to distinguish `update` so that only the relevant fields are included. If you send the whole patch to the `updateApplicationLink` rpc you will get an error because you use invalid field masks.
```suggestion
      const { skip_payload_crypto, ...applicationUpdate } = update
      const linkUpdate = { skip_payload_crypto }
      await updateApplication(application_id, applicationUpdate)
      await updateApplicationLink(application_id, linkUpdate)
```

2021-11-22 11:04 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        })
I guess this is WIP?

2021-11-25 08:47 UTC, kschiffer requested changes
Almost there. Have some remarks mainly about cypress and wording.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        cy.findByLabelText('Payload').should('be.disabled')
```suggestion
```
I think it's enough to check for the button only.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        )
Only use intercepts if absolutely necessary. In the end-to-end tests we try to reproduce usage as closely as possible, this includes relying on actual API responses wherever possible. 
In this case, you could either actually update the end device using a `PUT` request, or initially create the end device with the desired configuration directly.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        )
See my comment above on using actual API responses.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        )
Also here.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        cy.findByLabelText('Payload').should('be.enabled')
```suggestion
```

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        cy.findByLabelText('Payload').should('be.enabled')
```suggestion
```

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        )
See above.

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/shared/skip-payload-crypto/edit.spec.js
> +        cy.findByLabelText('Payload').should('be.disabled')
```suggestion
```

2021-11-25 08:47 UTC, kschiffer commented on cypress/integration/console/applications/edit.spec.js
> +      .should('be.visible')
```suggestion
      .findByText(`Application updated`)
      .should('be.visible')
```
I know we use the assertions like that in other places, but this is actually an unnecessary duplicate check, so let's not do that.

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +  default: 'Use default',
```suggestion
  default: 'Use application default',
```

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +  skip: 'Skip payload crypto',
```suggestion
  skip: 'Enforce skipping payload crypto',
```

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +  include: 'Do not skip payload crypto',
```suggestion
  include: 'Enforce payload crypto',
```

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +        horizontal
```suggestion
```

Given the longer option names (see above), I think we should use the vertical layout after all.

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +        required
```suggestion
```
Radio button options can never be `required` since there is always an option selected already.

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
>          title={sharedMessages.skipCryptoTitle}
Let's use a different massage here, reading `Payload crypto override`.

2021-11-25 08:47 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
> +        <RadioButton label={m.default} value="default" />
```suggestion
        <RadioButton label={m.default} value="default" />
        <RadioButton label={m.skip} value="skip" />
        <RadioButton label={m.include} value="include" />
```

2021-11-25 08:53 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/application-server-form/index.js
>          title={sharedMessages.skipCryptoTitle}
Let's also add a tooltip:

> Skip payload crypto disables the application layer encryption of LoRaWAN frames. This causes the Application Server to forward the messages without any processing, such as payload formatters, to the integrations.  When doing so, the integrations are responsible for decryption and processing of the binary format in order to understand the message. 
> 
> This application-wide setting can be overwritten per end device using this overwrite setting.

2021-11-26 07:06 UTC, htdvisser commented
This did not make it to the v3.16.1 deadline. Pushing to v3.16.2.

2021-11-26 11:48 UTC, kschiffer approved these changes
LGTM, see my remaining remark on the message naming.

2021-11-26 11:48 UTC, kschiffer commented on pkg/webui/lib/field-description-messages.js
> +  skipPayloadCryptoOverride:
```suggestion
  skipPayloadCryptoOverrideDescription:
```

2021-11-26 16:02 UTC, merged