Add administrative and technical contacts to replace contact info
TheThingsNetwork/lorawan-stack pull request #4996
Opened 2021-12-15 11:04 UTC by htdvisser

#### Summary

This pull request adds `administrative_contact` and `technical_contact` to applications, OAuth clients, gateways and organizations.

Refs #4930.

![Screen Shot 2021-12-15 at 11 46 41](https://user-images.githubusercontent.com/181308/146175259-f7eb3e13-2b4a-4ecd-8d1b-19028909063f.png)
![Screen Shot 2021-12-15 at 11 46 46](https://user-images.githubusercontent.com/181308/146175268-8ebac726-7551-4e15-81f3-06e52b25a40e.png)
![Screen Shot 2021-12-15 at 11 48 58](https://user-images.githubusercontent.com/181308/146175271-24865d43-54f5-4666-a33a-3fe792cfb90b.png)

#### Changes

- Define API
- Define Database Models in the IS
- Modify stores to handle creates/updates with contacts
- Modify Update RPCs to handle creates/updates with contacts
- Update CLI to allow un-setting contacts
- Add Console support (incomplete, help wanted)
	- [ ] Component to select one of the collaborators
	- [x] Application: Create
	- [x] Application: Overview
	- [ ] Application: Update (needs that component from above)
	- [x] Gateway: Create
	- [x] Gateway: Overview
	- [ ] Application: Update (needs that component from above)
	- [ ] Organization: Create
	- [x] Organization: Overview
	- [ ] Organization: Update (needs that component from above)

#### Testing

- Updated IS unit tests
- Console: help wanted

##### Regressions

n/a

#### Notes for Reviewers

Still TODO:

- [ ] Finish Console (help wanted from @kschiffer / @bafonins / @ryaplots)
- [ ] CHANGELOG

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-12-20 16:08 UTC, kschiffer commented
Let's move the settings for admin and tech contact to the application/gateway general settings to keep creation forms lean. It is sufficient to be able to set this setting after creation. By default, I think we can assume that the initial owner is admin and tech contact or does something speak against that?

2021-12-20 16:30 UTC, kschiffer commented
I've created an issue for a better way of selecting users/orgs here: #5027

2021-12-27 09:16 UTC, htdvisser commented
I'm going to rebase and force-push this branch so that it doesn't diverge too much.

2021-12-28 09:27 UTC, htdvisser commented
In order to move this forward, I've removed my commits that implemented _setting_ entity contacts in the Console. Hopefully somewhere in the future our frontend devs have time to implement that properly, and otherwise I can try to spend some more time on it after #4935 and #4936.

2021-12-29 09:11 UTC, johanstokking approved these changes
API changes LGTM

2021-12-29 09:38 UTC, htdvisser commented
Added two additional commits to:

1. Always set the collaborator as entity contact on create
2. Set the first organization collaborator, and otherwise the first user collaborator, as entity contact (in a migration)

For convenience, here's what the migration for applications looks like:

```sql
SELECT
    applications.id application_uuid,
    accounts.id account_uuid,
    FIRST_VALUE (accounts.id) OVER (
        PARTITION BY applications.id
        ORDER BY
            accounts.account_type ASC, -- Prefer organization contacts over user contacts
            memberships.created_at     -- Prefer the oldest collaborator
    ) first_account_uuid
FROM
    accounts
    JOIN memberships ON accounts.id = memberships.account_id
    JOIN applications ON applications.id = memberships.entity_id
    AND memberships.entity_type = 'application'
WHERE
    accounts.deleted_at IS NULL
    AND memberships.rights && ARRAY [
    28, -- RIGHT_{ENTITY}_ALL
    55  -- RIGHT_ALL
  ]
)
UPDATE
    applications
SET
    administrative_contact_id = application_owners.account_uuid,
    technical_contact_id = application_owners.account_uuid
FROM
    application_owners
WHERE
    applications.id = application_owners.application_uuid
    AND applications.administrative_contact_id IS NULL
    AND applications.technical_contact_id IS NULL
    AND application_owners.account_uuid = application_owners.first_account_uuid;
```

2021-12-29 10:51 UTC, bafonins requested changes

2021-12-29 10:51 UTC, bafonins commented on pkg/webui/console/components/contact/index.js
> +        <Message content={sharedMessages.none} />
```suggestion
        <Message className="tc-subtle-gray" component="i" content={sharedMessages.none} />
```

2021-12-29 10:51 UTC, bafonins commented on pkg/webui/console/components/contact/index.js
> +  const id = isUser ? props.ids.user_ids.user_id : props.ids.organization_ids.organization_id
```suggestion
  const id = getCollaboratorId({ids: props.ids})
```

from https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.17/pkg/webui/lib/selectors/id.js#L46-L48

2021-12-29 10:51 UTC, bafonins commented on pkg/webui/console/components/contact/index.js
> +      <Icon icon={icon} className={style.collaboratorIcon} /> {id}
```suggestion
      <Icon icon={icon} className={style.collaboratorIcon} nudgeUp /> {id}
```

2022-01-03 10:57 UTC, kschiffer reviewed
While the code looks good to me, I think that the utility of the new contact info is quite limited:
- Only the names of the orgs/users is provided without click-through
- We miss public profiles of orgs and users, which makes it impossible for non-admin users to watch/interact with other users
- Organizations often have no contact info associated with them, making it impossible to contact

We should at least add the public contact info to the name as a link (if present) next to the name.

2022-01-04 15:28 UTC, bafonins approved these changes
Please see my comment. `webui` changes look good, but please wait for @kschiffer approval as well

2022-01-04 15:28 UTC, bafonins commented on pkg/webui/console/components/contact/index.js
> +      <i>
You can remove the wrapping `<i />`. `component="i"` on L31 `<Message />` will be rendered as `<i />`

2022-01-04 15:40 UTC, htdvisser commented
@kschiffer already gave an LGTM on the code yesterday, but at this point I can't address his other suggestions. So if those are blockers for his approval, I can just omit the Console commits entirely.

This already has taken more time than it should have, and I want to get this merged today.

2022-01-04 15:44 UTC, kschiffer requested changes
Let's please extract the console part from this then for now and move it to a branch for reference as I am afraid that in its current form it creates more problems than it solves.

2022-01-04 15:54 UTC, kschiffer approved these changes

2022-01-04 16:11 UTC, merged