Add export event log button
TheThingsNetwork/lorawan-stack pull request #5029
Opened 2021-12-20 18:09 UTC by ryaplots

#### Summary

This pull request adds button to download the live data.
Closes #2383 

#### Changes

- Added export button and onExport() function

#### Testing

Run e2e tests and manually

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2021-12-21 12:10 UTC, kschiffer requested changes
Works well but please fix the responsive styling.

![image](https://user-images.githubusercontent.com/5710611/146925854-b4a02299-0763-440c-bf02-ab8b25485c2f.png)

The responsive styling has been problematic there for a while already. What would help here is hiding the headers (`Time`, `Type`, `Data`, `Entity`) in mobile views. Then, the buttons can move to the right and should also use the `responsiveLabel` prop.

2021-12-21 12:10 UTC, kschiffer commented on pkg/webui/console/components/events/index.js
> +      downloadDataUriAsFile(eventLogData, 'tts_live_data.json')
```suggestion
      downloadDataUriAsFile(eventLogData, `${entityId}_live_data_${Date.now()}.json`)
```

2021-12-21 16:01 UTC, ryaplots commented
After the last changes it would look like this:
<img width="760" alt="Screenshot 2021-12-21 at 14 51 00" src="https://user-images.githubusercontent.com/56658938/146960766-fccc255c-1c5e-48c2-95e5-3cf44346c19d.png">
<img width="964" alt="Screenshot 2021-12-21 at 14 51 18" src="https://user-images.githubusercontent.com/56658938/146960776-ef93ed20-d0ce-4fd0-9474-5b56d09dd39f.png">
<img width="797" alt="Screenshot 2021-12-21 at 14 54 20" src="https://user-images.githubusercontent.com/56658938/146960779-a834cbdc-be24-487e-bd10-abd6b7d0edea.png">

2021-12-22 08:47 UTC, bafonins approved these changes

2022-01-03 13:22 UTC, kschiffer approved these changes
Please also apply the following diff:
```udiff
diff --git a/pkg/webui/components/button/button.styl b/pkg/webui/components/button/button.styl
index ea4473ab0..13a61d620 100644
--- a/pkg/webui/components/button/button.styl
+++ b/pkg/webui/components/button/button.styl
@@ -138,6 +138,7 @@ $button($color)
         margin-right: $cs.xs
 
     &.responsive-label
+      padding: $cs.xs
       +media-query($bp.xxs)
         span:first-child
           margin-left: 0
diff --git a/pkg/webui/console/components/events/events.styl b/pkg/webui/console/components/events/events.styl
index 077645d17..d9d7b5ba4 100644
--- a/pkg/webui/console/components/events/events.styl
+++ b/pkg/webui/console/components/events/events.styl
@@ -48,7 +48,7 @@ $event-container-height = 40px
     font-weight: $fw.bold
     +media-query($bp.s)
         display: none
-  
+
   .cell-data
     +media-query($bp.l)
         display: none
@@ -70,14 +70,17 @@ $event-container-height = 40px
   flex-grow: 1
   right: $cs.s
   display: flex
-  justify-content: flex-end
   +media-query-min($bp.xs)
+    justify-content: flex-end
     position: sticky
 
   .actions
     background-color: white
     display: flex
 
+    button
+      margin-right: 0 !important
+
 .toggle-container
   display: flex
   align-items: center
```

2022-01-03 14:14 UTC, merged