ci: Update GoReleaser to v1.2.5
TheThingsNetwork/lorawan-stack pull request #5082
Opened 2022-01-11 11:53 UTC by michalborkowski96

#### Summary
Closes #5010 

#### Changes
Updated GoReleaser

#### Testing
Did not test, but did checks mentioned in the issue

##### Regressions
Release action might break

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-01-12 07:55 UTC, htdvisser requested changes
@michalborkowski96, how do you expect us to approve this when you say you haven't tested it, and you say that the exact thing that you're changing might break?

Please think about how you can test this so that we can be a little more confident than "it might break".

2022-01-12 08:12 UTC, KrishnaIyer commented
This is still in review and not going to make it to `v3.17.1`. Moving the milestone.

2022-01-13 08:53 UTC, michalborkowski96 commented
@htdvisser 

https://github.com/TheThingsNetwork/lorawan-stack/actions/runs/1691783657

2022-01-13 09:51 UTC, htdvisser approved these changes

2022-01-13 10:19 UTC, adriansmares approved these changes

2022-01-13 10:26 UTC, merged