`ping_slot_frequency` invalid field
TheThingsNetwork/lorawan-stack pull request #5116
Opened 2022-01-20 08:36 UTC by ryaplots

#### Summary

This PR fixes part of [sentry issue](https://sentry.io/organizations/the-things-industries/issues/2298261705/events/597f313761584ce2be2361edf4ecc694/?project=2682566&query=frontendOrigin%3ATrue+is%3Aunresolved&sort=freq&statsPeriod=14d). 

#### Changes

- Change condition for showing `ping_slot_frequency` form field according to what I wrote in #tts and discussion with Adrian.
- Make sure the field value makes it into patch.

#### Testing

Manually. 
It should be possible now to enable `class B` when `ping_slot_frequency` is not already set.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-01-24 07:55 UTC, bafonins approved these changes

2022-01-24 09:49 UTC, kschiffer requested changes

2022-01-24 09:49 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/network-server-form/index.js
> +      }
This should be solved via the validation schema in `/console/views/device-general-settings/network-server-form/validation-schema.js`

2022-02-01 16:09 UTC, kschiffer requested changes

2022-02-01 16:09 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/network-server-form/index.js
> +
Please remove.

2022-02-01 16:09 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js
> +                .required(sharedMessages.validateRequired)
You should additionally also conditionally set the `required` prop on the field component itself.

2022-02-04 16:27 UTC, kschiffer requested changes

2022-02-04 16:27 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js
> +              .required(sharedMessages.validateRequired)
This is not working, I can still submit the form with an empty ping slot frequency when class B is enabled (resulting in a submit error). This should be caught on validation level already. Please check what's the issue there.

2022-02-08 12:41 UTC, htdvisser commented
Removed reviewers and labels that were automatically added before the base branch change

2022-02-16 16:01 UTC, ryaplots commented
This PR is temporarily on hold until we come up with a good solution for this.

2022-04-11 12:34 UTC, kschiffer commented
Let's close this until we have a plan to resolve the general issue of mac settings validation.

2022-04-11 12:34 UTC, closed without merging