Fix: gateway_server_address containing scheme or port
TheThingsNetwork/lorawan-stack pull request #5283
Opened 2022-03-02 22:08 UTC by onsolutionjames

#### Summary

Closes #5198 

#### Changes

 - Use getHostFromUrl() on the gateway_server_address, to strip any included scheme, port, etc

#### Testing

...

##### Regressions

...

#### Notes for Reviewers

...

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-03-11 13:54 UTC, kschiffer commented
@onsolutionjames do you plan on making the suggested change? Otherwise, I will close and recreate the PR.

2022-03-11 23:17 UTC, onsolutionjames commented
Hi @kschiffer, I'm not sure what changes you're referring to? On the original issue you said it was good to go, see here: https://github.com/TheThingsNetwork/lorawan-stack/issues/5198#issuecomment-1057063701

Let me know if there are any changes I need to make though and I'll get on to them ASAP

2022-03-24 12:45 UTC, kschiffer requested changes

2022-03-24 12:45 UTC, kschiffer commented on CHANGELOG.md
> +- Fix incorrect handling of gateway_server_address in the console when it contains a scheme or port
```suggestion
- Console determining gateways as "Other cluster" even though using the same host if server addresses not matching exactly (e.g. due to using different host or scheme)
```

2022-03-24 12:46 UTC, kschiffer commented
Hi @onsolutionjames, very sorry. I only see now that I hadn't actually submitted my review :facepalm: .

Can you make the change to the changelog? Then we can merge.

2022-03-25 06:09 UTC, onsolutionjames commented
Hi @kschiffer, I've just made this update to the changelog as requested. Let me know if there is anything else for me to do

2022-03-25 10:15 UTC, kschiffer approved these changes

2022-03-25 10:16 UTC, merged

2022-03-25 10:48 UTC, onsolutionjames commented
Hi @kschiffer, it looks like this was added under the 3.18.0 heading in the changelog, which I'm guessing probably isn't ideal as 3.18.0 has already been released. Is there anything I should do to fix that? (or something I should have done to prevent it from happening?)

<img width="1080" alt="Screen Shot 2022-03-25 at 9 44 03 pm" src="https://user-images.githubusercontent.com/69997327/160106607-55742248-c829-4401-b7d8-711bc155c76b.png">

2022-03-25 10:50 UTC, kschiffer commented
Indeed. I'll fix that. Thank you!