Feature/gateway visibility packet broker
TheThingsNetwork/lorawan-stack pull request #5294
Opened 2022-03-09 09:06 UTC by ryaplots

#### Summary

This PR implements Console support for gateway visibility on Packet Broker.
Closes #4409 

#### Changes

- Added a "Default gateway visibility" tab
- Gateway visibility form
- Cypress tests

#### Testing

Manually and cypress tests

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-03-09 10:08 UTC, ryaplots commented on pkg/webui/console/store/actions/packet-broker.js
> +] = createRequestActions(DELETE_HOME_NETWORK_DEFAULT_GATEWAY_VISIBILITY_BASE)
I didn't delete this action, in case it is needed in the future, although I am not currently using it in the form.

2022-03-09 14:12 UTC, kschiffer requested changes
Very good! I have only small comments regarding wording and the e2es.

2022-03-09 14:12 UTC, kschiffer commented on cypress/integration/console/packet-broker/default-gateway-visibility.spec.js
> +    cy.findByTestId('error-notification').should('not.exist')
Please additionally check whether the intercepted endpoint has been actually called.
We saw issues last week where no changes have been retained even though the success message appeared causing false positives, so we have to extend the form tests a bit to rule that out. Usually we could refresh the page but since here we're using stubs, we can just verify if the request was made:

```js
cy.intercept('PUT', '/api/v3/pba/home-networks/gateway-visibilities/default', {}).as('putCall')
...
cy.get('@putCall').its('callCount').should('eq', 1)
```
(haven't tested this)

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/components/gateway-visibility-form/index.js
> +        <Form.Submit component={SubmitButton} message={submitMessage} />
```suggestion
        <Form.Submit component={SubmitButton} message={m.saveDefaultGatewayVisibility} />
```
Not required to pass the message as a prop, unless you actually need to be able to control the button message for different contexts.

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/views/admin-packet-broker/messages.js
> +    'You can use the checkboxes below to control the default gateway visibility configuration.',
```suggestion
    'You can use the checkboxes below to control what information your gateways will expose when interacting with other registered networks.',
```
@johanstokking pls ACK

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayLocationDescription: 'Show location',
```suggestion
```
Some of these are actually too repetitive, so let's remove or change those.

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayAntennaCountDescription: 'Show antenna count',
```suggestion
```

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayContactInfoDescription: 'Show contact information',
```suggestion
  gatewayContactInfoDescription: 'Show means to contact the gateway owner or operator',
```

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayStatusDescription: 'Show status (online/offline)',
```suggestion
  gatewayStatusDescription: 'Whether the gateway is online or offline',
```

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayFreqPlanDescription: 'Show frequency plan',
```suggestion
```

2022-03-09 14:12 UTC, kschiffer commented on pkg/webui/console/lib/packet-broker/messages.js
> +  gatewayPacketRatesDescription: 'Show receive and transmission packet rates',
```suggestion
  gatewayPacketRatesDescription: 'Receive and transmission packet rates',
```

2022-03-10 09:58 UTC, ryaplots commented
I have resolved all conversions. The only thing needed is Johan's confirmation on that message.

2022-03-10 17:19 UTC, johanstokking commented on pkg/webui/console/views/admin-packet-broker/messages.js
> +    'You can use the checkboxes below to control the default gateway visibility configuration.',
Maybe "You can use the checkboxes to control what information of your gateways will be visible"

This is a _default_ visibility, meaning that it's visible to anyone, even the public (so not only registered networks)

2022-03-10 17:19 UTC, johanstokking commented
Great, see my comment above

2022-03-11 09:25 UTC, kschiffer approved these changes

2022-03-11 09:25 UTC, kschiffer commented on CHANGELOG.md
> +- Default gateway visibility configuration in packet broker agent in the Console.
```suggestion
- Default gateway visibility configuration in Packet Broker agent in the Console.
```

Is more consistent.

2022-03-11 10:02 UTC, merged