Various table improvements
TheThingsNetwork/lorawan-stack pull request #5497
Opened 2022-05-30 14:11 UTC by kschiffer

#### Summary
This PR improves the UX around data displayed in tables in the Console in various ways.

<details><summary>See screenshots</summary>

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/5710611/171008933-9f81638e-7c7d-4559-9c75-e62882e34944.png">
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/5710611/171009000-cc55cec3-df22-47e1-9106-ce5182076416.png">
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/5710611/171009032-86d6da0c-e4f9-4ca7-8128-c2ba3c7224a0.png">
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/5710611/171009162-621d14d4-3c77-4553-80aa-285c9e25f6fd.png">
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5710611/171009221-7923fabf-8e3c-44f9-a7b0-d1c585914116.png">

</details>

#### Changes
- Improve column widths across entity tables
- Add `created_at` column to several entity tables
- Sort by `created_at` (latest first) by default (except for collaborators)
- Add sorting functionality for API keys, collaborators, pubsubs and webhooks
- Streamline right-tags inside API key and collaborator tables
  - Use localized right description per right
  - Use tooltips for overflowed content
  - Use tooltips for omitted rights counter
- Add number of devices per application entry in the applications table
  - Extend store logic to retrieve device count for list action
- Add number of collaborators per organization in the organizations table
  - Extend store logic to retrieve collaborator count for list action
- Add missing RPC fields and backend functionality for sorting API keys
- Small related styling fixes

#### Testing

Manual and existing e2es.

##### Regressions

None.

#### Notes for Reviewers
Sorting for collaborators is now solved in the frontend using a `limit` of `1000` and disabling sorting if the total count is above that. It felt like an acceptable compromise to me after looking into the complexity of sorting in the backend that uses a composed join of orgs and users which makes sorting quite complicated (to me).

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-05-31 07:47 UTC, htdvisser requested changes
Blocking this PR on a proper sorting implementation in the backend. I'll try to pick that up somewhere this week.

2022-06-02 08:54 UTC, adriansmares commented on CHANGELOG.md
> -- Entities are now fully validated when updated in the stores.
Don't drop the old changelog.

2022-06-02 08:54 UTC, adriansmares commented on pkg/webui/console/containers/pubsubs-table/index.js
> +        handlesSorting
This should be `paginated=false` too, right ?

2022-06-02 11:33 UTC, adriansmares approved these changes

2022-06-02 11:58 UTC, htdvisser approved these changes

2022-06-07 14:29 UTC, ryaplots approved these changes
code-owned changes lgtm

2022-06-08 02:49 UTC, nicholaspcr approved these changes
Approving since the code-owned files changes were reverted.

Important question @htdvisser
>Blocking this PR on a proper sorting implementation in the backend. I'll try to pick that up somewhere this week.

Was it done already? Or is it being added on the rewrite?
I wanted to read it but I couldn't find the PR.

2022-06-08 07:30 UTC, htdvisser commented
This was indeed done. You don't see my commits because @kschiffer squashed them into his original commits.

2022-06-08 07:32 UTC, htdvisser requested changes
Actually, after taking another look, it seems my commits were dropped from this PR.

2022-06-09 06:14 UTC, htdvisser approved these changes

2022-06-09 08:07 UTC, merged