Fix application collaborator deletion in Console
TheThingsNetwork/lorawan-stack pull request #5833
Opened 2022-09-28 12:36 UTC by kschiffer

#### Summary
This quickfix PR fixes an issue in the Console, where after successfull deletion of a collaborator, the collaborator would still be shown in the collaborators list.

#### Changes

- Remove redirect and toast from deletion handler (redirect and toast are done via `onDeleteSuccess`)
- Move the collaborator form from `components` to `containers`
- Update e2es

#### Testing

- Manual testing
- Updating the e2es so that this error would be caught

##### Regressions

None.

#### Notes for Reviewers
@ryaplots The collaborator form has been moved into the `components` in one of your recent account app PRs. Note that the form connects to the store and is hence a container.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-09-28 12:39 UTC, mjamescompton requested changes

2022-09-28 12:39 UTC, mjamescompton commented on pkg/webui/console/views/organization-collaborator-edit/organization-collaborator-edit.js
> +            onDeletete={removeOrganizationCollaborator}
Should this be `onDeleted`

2022-09-28 12:42 UTC, kschiffer commented on pkg/webui/console/views/organization-collaborator-edit/organization-collaborator-edit.js
> +            onDeletete={removeOrganizationCollaborator}
Oopsie

2022-09-29 06:45 UTC, ryaplots approved these changes

2022-09-29 08:13 UTC, mjamescompton approved these changes

2022-09-29 08:14 UTC, merged