console: Allow dynamic frequencies and hide desired fields
TheThingsNetwork/lorawan-stack pull request #5969
Opened 2022-12-06 17:23 UTC by kschiffer

#### Summary
Fixes #5893

#### Changes

- Allow setting `0` as a frequency value for ping slot and beacon frequency (meaning dynamic frequency)
- Hide desired MAC fields when using multicast end devices

#### Testing

Manual testing.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-12-07 09:42 UTC, mjamescompton requested changes

2022-12-07 09:42 UTC, mjamescompton commented on pkg/webui/console/components/mac-settings-section/index.js
> +        !isMulticast(
This is not a function

2022-12-07 09:42 UTC, mjamescompton commented on pkg/webui/console/components/mac-settings-section/index.js
> +        !isMulticast(
Error on expanding network layer on device general settings

2022-12-07 09:42 UTC, mjamescompton commented on pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js
>            beacon_frequency: Yup.lazy(frequency => {
frequency is declared but never read

2022-12-07 09:42 UTC, mjamescompton commented on pkg/webui/console/views/device-general-settings/network-server-form/validation-schema.js
>            desired_beacon_frequency: Yup.lazy(frequency => {
frequency is declared but never read

2022-12-08 08:13 UTC, ryaplots approved these changes
lgtm

2022-12-08 09:41 UTC, merged