Un-claim on delete
TheThingsNetwork/lorawan-stack pull request #5972
Opened 2022-12-08 14:44 UTC by mjamescompton

#### Summary

Closes https://github.com/TheThingsNetwork/lorawan-stack/issues/5836

#### Changes

- Set all delete requests to use body instead of query params
- Add handleUnclaim to device general settings 

#### Testing

...

#### Notes for Reviewers

2022-12-12 10:07 UTC, kschiffer requested changes

2022-12-12 10:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/connect.js
> +      }) => getInfoByJoinEUI({ join_eui: joinEUI }),
You can use the `mergeProps` to compose the action with the join eui.

2022-12-12 10:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/connect.js
> +      }) => getInfoByJoinEUI({ join_eui: joinEUI }),
I'd suggest fetching the claim info on the `/views/device` level instead since we might use that info in other places eventually.

2022-12-12 10:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/identity-server-form/index.js
> +    // Check if device is claimable if so try to unclaim.
```suggestion
    // Check if device is claimable and if so, try to unclaim.
```

2022-12-12 10:07 UTC, kschiffer commented on pkg/webui/console/views/device-general-settings/messages.js
> +  unclaimFailure: 'An error occurred and the end device could not be unclaimed',
```suggestion
  unclaimFailure: 'An error occurred and the end device could not be unclaimed and deleted',
```

2022-12-13 10:24 UTC, mjamescompton commented
@KrishnaIyer What is your advice on how to test this before putting it live, could you take over a test this on staging?

2022-12-13 10:38 UTC, KrishnaIyer commented
If this gets reviewed, unit tested and merged into TTS, I can deploy a snapshot and run a test.

2022-12-13 10:41 UTC, kschiffer commented
Ok, let's add a small cypress test-case then which tests against the unclaim API request shape.

2022-12-14 08:47 UTC, ryaplots approved these changes

2022-12-15 13:59 UTC, kschiffer approved these changes

2022-12-15 13:59 UTC, kschiffer commented on cypress/integration/console/devices/unclaim.spec.js
> +// Copyright © 2021 The Things Network Foundation, The Things Industries B.V.
```suggestion
// Copyright © 2022 The Things Network Foundation, The Things Industries B.V.
```

2022-12-20 10:46 UTC, merged