Add proto unimplemented to GRPC Servers
TheThingsNetwork/lorawan-stack pull request #5978
Opened 2022-12-16 12:52 UTC by cvetkovski98

#### Summary
This PR adds `ttnpb.Unimplemented<Server>` to RPC Servers

References #2798

#### Changes

- Adds `ttnpb.Unimplemented<ServerName>` to every RPC Server used in a `ttnpb.Register<ServerName>Server()`

#### Testing
- Existing Unit Tests

##### Regressions

...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-12-16 13:08 UTC, KrishnaIyer requested changes
Please fix the commit messages https://github.com/TheThingsIndustries/lorawan-stack/pull/3509#issuecomment-1354740509

2022-12-16 14:17 UTC, adriansmares approved these changes

2022-12-16 15:22 UTC, KrishnaIyer approved these changes
LGTM

2022-12-19 11:04 UTC, johanstokking commented
No more need for my review!

2022-12-19 11:20 UTC, merged