Fix csv import first column skip
TheThingsNetwork/lorawan-stack pull request #5981
Opened 2022-12-19 13:44 UTC by nicholaspcr

#### Summary

Closes https://github.com/TheThingsIndustries/lorawan-stack-support/issues/892

Basically there were some cases where the CSV import would not consider the value of the ID column in the csv file, this in fact was not a problem with the ID column but the first column present in the header of any file that contained the BOM (Byte Order Mark) bytes.

#### Changes

- Trim bytes of BOM bytes if present
- ...

#### Testing

Manual testing, used the CSV file provided in the issue and also tested the import with a json file.

##### Regressions

This is a bug fix, the only thing that could be affected by this change would be the JSON import but that was tested.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2022-12-19 13:55 UTC, KrishnaIyer requested changes

2022-12-19 13:55 UTC, KrishnaIyer commented on pkg/devicetemplateconverter/grpc.go
> +		if err := converter.Convert(ctx, bytes.NewReader(trimmedBytes), ch); err != nil {
At this point, we don't yet know the encoding of `req.Data` right? 
The data is interpreted as UTF-8 in the [converter](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.23/pkg/devicetemplates/ttscsv.go#L361).

I think this trimming should be there as well.

2022-12-19 14:01 UTC, adriansmares commented on pkg/devicetemplateconverter/grpc.go
> +		if err := converter.Convert(ctx, bytes.NewReader(trimmedBytes), ch); err != nil {
I think that no trimming should take place, and instead we should check why the `charset` reader is not removing the BOM.

2022-12-19 14:05 UTC, nicholaspcr commented on pkg/devicetemplateconverter/grpc.go
> +		if err := converter.Convert(ctx, bytes.NewReader(trimmedBytes), ch); err != nil {
Its not specified in https://www.rfc-editor.org/rfc/rfc4180.html which is what `enconding/csv` is defined on.
So its something added by excel and not exactly expected.

Indeed maybe instead of adding it in the dtc I could peek at the first bytes and remove them if they match the BOM

2022-12-19 14:27 UTC, adriansmares commented on pkg/devicetemplateconverter/grpc.go
> +		if err := converter.Convert(ctx, bytes.NewReader(trimmedBytes), ch); err != nil {
I am referring to the conversion at https://github.com/TheThingsNetwork/lorawan-stack/blob/55212be1049e8c85ab7c3b752172051a2d30e2f9/pkg/devicetemplates/ttscsv.go#L357-L364 - [charset](https://pkg.go.dev/golang.org/x/net/html/charset) should automatically remove the BOM and convert the text to UTF-8. You should not see the BOM in UTF-8 after the conversion.

2022-12-19 14:30 UTC, adriansmares commented on pkg/devicetemplateconverter/grpc.go
> +		if err := converter.Convert(ctx, bytes.NewReader(trimmedBytes), ch); err != nil {
By the time you have reached the decoder it is guaranteed to be converted to UTF-8:
https://github.com/TheThingsNetwork/lorawan-stack/blob/55212be1049e8c85ab7c3b752172051a2d30e2f9/pkg/devicetemplates/ttscsv.go#L357-L364

What could happen is indeed that our header character parsing does not handle this correctly - please fix that one instead.

2022-12-20 14:05 UTC, adriansmares commented on pkg/devicetemplates/ttscsv.go
> +		if ok := isBOM(head); ok {
Could we instead peek the first rune (`buf.ReadRune()`) after we initialize `buf`, and then compare it with `'\uFEFF'` ? That's a bit more idiomatic than byte comparison and handling.

If the first rune is not `'\uFEFF'`, we can use `buf.UnreadRune()`.

2022-12-21 11:12 UTC, adriansmares approved these changes

2022-12-23 15:35 UTC, nicholaspcr commented
@KrishnaIyer, a gentle reminder of this.

2022-12-26 07:30 UTC, KrishnaIyer approved these changes
Ah sorry. I thought @adriansmares's review was enough. Good stuff.

2022-12-26 11:28 UTC, merged