Add default error values for backend-origin messages
TheThingsNetwork/lorawan-stack pull request #6080
Opened 2023-02-27 14:46 UTC by ryaplots

#### Summary

Closes #6003
Complements #6078 

#### Changes

- Add default values for messages coming from the backend

#### Testing

e2e and manually (use payload from the [issue](https://github.com/TheThingsNetwork/lorawan-stack/issues/6003))

#### Notes for Reviewers

`Intl` throws an error if one of the values of a message is missing. The way I found to avoid this was to add a default, to which the value falls back if not set in attributes by the backend.

So for this payload:
```
"cause": {
       "namespace": "pkg/gatewayserver/scheduling",
       "name": "too_late",
       "message_format": "too late to transmission scheduled time (delta is `{delta}`, min is `{min}`)",
       "attributes": {
              "min": "1.771613169s"
       },
       "correlation_id": "69ed7acf7d0a424f860ec52971c97b78",
       "code": 9
},
```
if `delta` is not present it will have the value of the default fallback.

My question is: is this really necessary? Aren't these attributes required? Are there situations where the attribute won't be there, other than a bug? @adriansmares

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-02-27 14:51 UTC, adriansmares commented
> My question is: is this really necessary? Aren't these attributes required? Are there situations where the attribute won't be there, other than a bug? @adriansmares @kschiffer

The attributes are unfortunately not required, and can be optional. In this case, it was a bug, but otherwise I think we should fail more softly (and maybe generate a Sentry error) if an attribute is missing.

Is it not possible to make `Intl` apply only present attributes and error for the remaining ones, instead of having defaults ? (which are also error prone, as they are just strings which are decoupled from the backend).

2023-03-01 10:05 UTC, ryaplots commented
I've spent some time looking through the [`Intl` documentation](https://formatjs.io/docs/react-intl/components/#message-formatting-fallbacks) and I couldn't find a way to fail softly.

We could generate default values if the placeholders in the message are more that the values in attributes, extracting `{value}` from the message, and also report the error to Sentry if this occurs and if `Intl` fails.
@kschiffer

2023-03-09 13:57 UTC, kschiffer requested changes
See my small suggestion. Please run some tests on staging. Any issues we introduce here can be very catastrophic since we use messages just about anywhere.

2023-03-09 13:57 UTC, kschiffer commented on pkg/webui/lib/components/with-locale.js
> +      return
```suggestion
```

2023-03-09 13:57 UTC, kschiffer commented on pkg/webui/lib/components/with-locale.js
> +      return
One problem with this is that this error will potentially fire hundreds of times when the message gets rerendered a lot. But let's keep it and see how much of a problem this is.

2023-03-09 13:57 UTC, kschiffer commented on pkg/webui/lib/errors/utils.js
> +          : {}
```suggestion
        const messageValues = rootCause?.message_format?.match(/[^{}]+(?=})/g) || []
        const fallbackValues = messageValues.reduce((obj, val) => ((obj[val] = `{${val}}`), obj), { ...rootCause.attributes })
        const values = { ...fallbackValues, ...rootCause.attributes }
```
Let's just always spread the existing values over the missing values.

2023-03-09 13:57 UTC, kschiffer commented on pkg/webui/lib/errors/utils.js
> +          values: { ...rootCause.attributes, ...defaultErrorValues },
```suggestion
          values,
```

2023-03-14 10:53 UTC, kschiffer requested changes

2023-03-14 10:53 UTC, kschiffer commented on pkg/webui/lib/errors/utils.js
> +        const values = { ...fallbackValues, ...rootCause.attributes }
```suggestion
        const values = messageValues.reduce((obj, val) => {
          if (!(val in obj)) {
            obj[val] = val
          }
          return obj
        }, { ...rootCause.attributes })
```

2023-03-14 10:53 UTC, kschiffer commented on pkg/webui/lib/errors/utils.js
> +        const values = { ...fallbackValues, ...rootCause.attributes }
Sorry, my last suggestion was odd.

2023-03-15 08:56 UTC, kschiffer approved these changes

2023-03-15 09:05 UTC, merged