Update device QR scanning communications
TheThingsNetwork/lorawan-stack pull request #6083
Opened 2023-03-01 13:48 UTC by mjamescompton

#### Summary

Close #5985

also see

https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1055

#### Changes

- Update `hasEndDeviceQR` and `invalidData` communications in the device onboarding

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-03-02 11:05 UTC, ryaplots approved these changes
Looks good to me! Only some CI is not passing

2023-03-07 10:31 UTC, kschiffer commented on pkg/webui/components/qr-modal-button/index.js
> +    'Invalid QR code data. Please scan a valid TR005 LoRaWAN® Device Identification QR Code. ',
```suggestion
    'Invalid QR code data. Please note that only TR005 LoRaWAN® Device Identification QR Code can be scanned. Some devices have unrelated QR codes printed on them that cannot be used.',
```

2023-03-07 10:33 UTC, kschiffer commented on pkg/webui/console/containers/device-onboarding-form/messages.js
> +    'Does your end device have a TR005 LoRaWAN® Device Identification QR Code? Scan it to speed up onboarding.',
```suggestion
    'Does your end device have a LoRaWAN® Device Identification QR Code? Scan it to speed up onboarding.',
```
Let's be less clunky.

2023-03-07 10:33 UTC, kschiffer requested changes
See my comments

2023-03-21 10:04 UTC, kschiffer approved these changes

2023-03-21 11:46 UTC, merged