Refactor/5587 contact info
TheThingsNetwork/lorawan-stack pull request #6307
Opened 2023-06-05 15:14 UTC by nicholaspcr

#### Summary

Reference #5587 

#### Changes

- Separate `ValidateContactInfo` into: GetValidation, ValidateContactInfo(only acts on ContactInfo) and ExpireValidation.

#### Testing

unit tests

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-06-06 14:38 UTC, adriansmares requested changes

2023-06-06 14:38 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +	if len(v.GetContactInfo()) == 0 {
Don't forget the span.

2023-06-06 14:38 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +) (*ttnpb.ContactInfoValidation, error) {
Don't forget the span.

2023-06-06 14:38 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +) (*ttnpb.ContactInfoValidation, error) {
Don't forget the span.

2023-06-06 14:38 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +func (s *contactInfoStore) ExpireValidation(ctx context.Context, v *ttnpb.ContactInfoValidation) error {
Don't forget the spans.

2023-06-06 14:38 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +	if len(v.GetContactInfo()) == 0 {
To be honest `!=1` is what I would check here.

2023-06-07 13:32 UTC, adriansmares approved these changes

2023-06-07 13:32 UTC, adriansmares commented on pkg/identityserver/bunstore/contact_info_store.go
> +	ctx, span := tracer.StartFromContext(ctx, "GetValidation", trace.WithAttributes(
Wrong span name.

2023-06-07 13:52 UTC, nicholaspcr commented
Re-requested the review by mistake @adriansmares

2023-06-07 13:56 UTC, adriansmares approved these changes

2023-06-07 17:19 UTC, merged