Update handleDelete of Collaborators in Console
TheThingsNetwork/lorawan-stack pull request #6491
Opened 2023-08-29 16:56 UTC by nicholaspcr

#### Summary

References #6489

Tried making a change on the Console so it uses the new HTTP route to perform collaborator deletion.

#### Changes

- Update collaborator-form's `handleDelete`
- Update collaborator actions

#### Testing

Manual testing and cypress tests should not break with this change.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-08-29 17:12 UTC, nicholaspcr commented
On a different note, while looking at the sdk I noticed that https://github.com/TheThingsNetwork/lorawan-stack/blob/e374556b528476bc320606433a4fbd51ad330ccc/sdk/js/src/service/devices/merge.js#L68-L71 is still present but the issue is closed. Thought it was worth mentioning.

2023-08-30 05:13 UTC, kschiffer requested changes

2023-08-30 05:13 UTC, kschiffer commented on pkg/webui/containers/collaborator-form/index.js
> +      removeCollaborator(isCollaboratorUser, collaboratorId)
```suggestion
      await removeCollaborator(isCollaboratorUser, collaboratorId)
```

2023-08-30 05:13 UTC, kschiffer commented on pkg/webui/lib/store/middleware/collaborators.js
> +      return tts[entitySdkServiceMap[parentType]].Collaborators.remove(isUser, parentId, collaboratorId)
```suggestion
      const result = await tts[entitySdkServiceMap[parentType]].Collaborators.remove(isUser, parentId, collaboratorId)
      
      return result
```

The reason to add this extra step is to ensure that errors during fetching are thrown in the correct scope.

2023-09-01 04:35 UTC, kschiffer approved these changes

2023-09-01 19:44 UTC, merged