Fix switch camera
TheThingsNetwork/lorawan-stack pull request #6613
Opened 2023-10-03 11:38 UTC by ryaplots

#### Summary

Closes #6529 

#### Changes

- Use a state for video mode

https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/9711301c-4915-4219-bfe6-2ff4d1361edf

#### Testing

1. Log in the console on a mobile device
2. Go to register end device
3. Click on scan end device QR code
4. See the switch button at the bottom of the video
5. Click and see the camera changing

#### Notes for Reviewers

Not using `stream` for conditions because at some point in time it is an empty object, which prevents comparing it's contents and makes it unreliable for the switch.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-10-04 12:28 UTC, mjamescompton commented
Is the clicking allow each time because of your set up or do you have to do that per camera?

2023-10-04 13:22 UTC, ryaplots commented
> Is the clicking allow each time because of your set up or do you have to do that per camera?

I think it's my setup

2023-10-04 13:30 UTC, mjamescompton commented
I have a feeling its every time you run `await navigator.mediaDevices.getUserMedia({` it resets the the user permissions.

2023-10-04 13:40 UTC, ryaplots commented
> I have a feeling its every time you run `await navigator.mediaDevices.getUserMedia({` it resets the the user permissions.

Might be. Let me test.

2023-10-04 14:27 UTC, kschiffer commented
Cool! Can we put the button on top of the camera stream instead? Right now it's causing this black bar at the bottom.
Also, can we fix the missing margin between the two "Cancel" and "Apply" button?

2023-10-13 14:11 UTC, mjamescompton requested changes
Could not get the switch to work on either iPhone 14 or Samsung Galaxy A10

<img width="1350" alt="Screenshot 2023-10-13 at 16 09 12" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/46600603/782ecea8-7e3b-40fc-aaac-dac372107572">

Nothing happens on the iPhone and above happens on the samsumg on chrome when I click the button

2023-10-13 14:11 UTC, mjamescompton commented on pkg/webui/components/qr/input/video/index.js
> +    if (videoMode.facingMode === 'environment') {
device: iPhone14 Pro
browser: safari

`videeMode.faceMode` === `{ exact: "environment" }`

There is no condition for this so the switch camera button does nothing.

2023-10-13 14:11 UTC, mjamescompton commented on pkg/webui/components/qr/input/video/index.js
>        {cameras.length > 1 && isMobile && (
`isMobile` I don't think this is needed.

2023-10-13 14:11 UTC, mjamescompton commented on pkg/webui/components/qr/input/video/index.js
>        {cameras.length > 1 && isMobile && (
`cameras.length` does not have a value when you first open the modal, you must close and re-open the model for the switch camera button to should. 

It might be better to always show the button and disable it if the device.length is 1 or less

2023-10-17 04:31 UTC, kschiffer approved these changes
LGTM, though haven't tested.

2023-10-19 09:00 UTC, mjamescompton requested changes
Ok, 

Iphone 14 pro - chrome  and safari - testing 

- switch camera button still does not show on first render of the modal
- switching the camera works once to go from back camera to front 
- but clicking the button again does nothing

I'm thinking we should put a component in between two we currently have. This one would specifically handle requesting the stream etc and includes the switching button, then we re-render the a component <Video stream="xxx">  because the `cameras.length` does not seem to cause a re render to show the button. The button could also always show but greyed out until the camera length is updated .

2023-10-19 11:19 UTC, mjamescompton approved these changes
Still broken but going ahead anyway.

I don't have an android phone to test, but I believe the switch button not rendering will be there as well, so I don't think anyone will see it anyway

2023-10-19 11:19 UTC, merged