Support setting multiple frequency plans for gateways from the Console
TheThingsNetwork/lorawan-stack pull request #6615
Opened 2023-10-04 15:23 UTC by ryaplots

#### Summary

Closes #6580 

#### Changes

- Add gateway frequency plan select field component
- Update entry and key value map components to allow updating options
- Refactor fetch select
- Update validation schema
- Display the various frequency plan ids in gateway overview and in the general settings
- Fix bytes component (error in the console)

https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/a8b13f42-5bee-4460-9a9a-a6b417d910ef

#### Testing

1. Go to register a gateway.
2. Add a couple of frequency plans and notice that the already selected plans are not in the options list.
3. If no frequency plans id is the form submit should not be possible.
4. Registering the gateway should be successful.
5. In the gateway overview see the selected frequency plans.
6. In the general settings change some of the frequency plans, refresh the page and see the newly selected frequency plans.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-10-05 11:16 UTC, kschiffer requested changes
Looking great. See my remarks.

2023-10-05 11:16 UTC, kschiffer commented on cypress/e2e/console/gateways/edit.spec.js
Let's add a test case for multiple FPs as well.

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  withOptionsUpdate,
```suggestion
  distinctOptions,
```
Better name IMO.

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  removeMessage: undefined,
```suggestion
  removeMessage: sharedMessages.remove,
```
Safe to set this as a default.

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  icon,
```suggestion
```
I don't think we need the icon configurable. We can still change this once needed.

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  const handleFocus = useCallback(() => {
It's better to set the handler only when needed, instead of always setting it and then using conditionals within, unless you have other functionality on focus that would always fire.

```jsx
<InputElement
   …
   onFocus={distinctOptions && options ? handleOptionComposition : undefined}
/>

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +          onClick={handleRemoveButtonClicked}
```suggestion
          onClick={handleRemoveButtonClick}
```

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  atLeastOneEntry,
I think we also don't need this as a prop, but can assume this to be true always. For non-required fields, you would just leave the last entry empty. Everything else should be validated in the respective validation schema.

2023-10-05 11:16 UTC, kschiffer commented on pkg/webui/console/containers/freq-plans-select/utils.js
> +  removeFrequencyPlan: 'Remove',
This is a message duplicate.

2023-10-06 08:55 UTC, ryaplots commented on pkg/webui/components/key-value-map/entry.js
> +  atLeastOneEntry,
You mean the `atLeastOneEntry` prop?
If so, the case of attributes, the validation schema checks for empty entries and does not allow them currently. We would need to refactor the schema to strip empty values.

2023-10-16 02:59 UTC, kschiffer commented on pkg/webui/components/key-value-map/entry.js
> +  atLeastOneEntry,
Yeah, let's change this so that fully empty entries will just be stripped/ignored.

2023-10-16 10:14 UTC, kschiffer approved these changes

2023-10-19 09:37 UTC, merged