Simplify Packet Broker settings
TheThingsNetwork/lorawan-stack pull request #6639
Opened 2023-10-18 13:03 UTC by ryaplots

#### Summary

Closes [#3838](https://github.com/TheThingsIndustries/lorawan-stack/issues/3838)

#### Changes

- Update packet broker main view
- Separate two forms
- Add radio button options
- Update e2e tests
- Remove gateway visibility

![Screenshot 2023-10-18 at 14-47-15 Management platform for The Things Stack for LoRaWAN](https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/5c4a0d5a-1f6d-462e-83ae-81f2d7dd6e59)

#### Testing

1. Open packet broker in the admin panel.
2. Select the first two options one at a time to make sure each one is successful.
3. Select custom configuration, go to the network tab and change a network config.
4. Reload the page see that the configuration you selected is the one shown.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-10-23 09:18 UTC, johanstokking requested changes
I tested this locally and I have a few issues:

1. If you select sandbox, it creates a policy with NetID `000013` but not tenant ID `ttn`. It should be with tenant ID `ttn` explicitly because that is the community network.
2. When I go from the first radio button (forward traffic to all networks) and save, there's indeed a default routing policy created. However, the home network routing policy with `00013` is still there. I think all other policies should be deleted
3. When I go back to the second radio button (forward to sandbox) and click save, I get the error [0]

[0]

```
{
  "code": 3,
  "message": "type mismatch, parameter: net_id, error: strconv.ParseUint: parsing \"NaN\": invalid syntax"
}
```

2023-10-23 13:18 UTC, ryaplots commented
> I tested this locally and I have a few issues:
> 
>     1. If you select sandbox, it creates a policy with NetID `000013` but not tenant ID `ttn`. It should be with tenant ID `ttn` explicitly because that is the community network.
> 
>     2. When I go from the first radio button (forward traffic to all networks) and save, there's indeed a default routing policy created. However, the home network routing policy with `00013` is still there. I think all other policies should be deleted
> 
>     3. When I go back to the second radio button (forward to sandbox) and click save, I get the error [0]
> 
> 
> [0]
> 
> ```
> {
>   "code": 3,
>   "message": "type mismatch, parameter: net_id, error: strconv.ParseUint: parsing \"NaN\": invalid syntax"
> }
> ```

1. When trying to create a policy with an explicit tenant id (this url: `https://tti.staging1.cloud.thethings.industries/api/v3/pba/home-networks/policies/19/ttn`) I get an error:
```
{
  "code": 10,
  "message": "error:unknown:unknown (bad reference)",
  "details": [
    {
      "@type": "type.googleapis.com/ttn.lorawan.v3.ErrorDetails",
      "message_format": "bad reference",
      "correlation_id": "fa423e90d1854199bb417f4497ffb3be",
      "code": 10
    }
  ]
}
```
I checked the [staging networks list](https://tti.staging1.cloud.thethings.industries/console/admin-panel/packet-broker/networks) and it seems like The Things Network network does not have a tenant id. Also when updating its policy the request is sent to `https://tti.staging1.cloud.thethings.industries/api/v3/pba/home-networks/policies/19`, which is why I used the same net_id and did not indicate a tenant ID.

2. I will update this.

3. Also looking into fixing this.

@johanstokking

2023-10-24 05:48 UTC, kschiffer commented
> If you select sandbox, it creates a policy with NetID 000013 but not tenant ID ttn. It should be with tenant ID ttn explicitly because that is the community network.

TTN is not on a tenant, is it? It's a single-tenant network, or what am I missing?

2023-10-24 08:00 UTC, johanstokking commented
> > If you select sandbox, it creates a policy with NetID 000013 but not tenant ID ttn. It should be with tenant ID ttn explicitly because that is the community network.
> 
> TTN is not on a tenant, is it? It's a single-tenant network, or what am I missing?

Yeah it actually is a tenant, but not on The Things Stack Cloud. The Things Stack Sandbox is a single tenant deployment that uses NetID `000013` and tenant ID `ttn`. For Packet Broker, there's no difference between `ttn` and TTSC tenants.

@ryaplots indeed the `ttn` tenant was missing on Packet Broker staging. It is there now.

2023-10-24 08:03 UTC, kschiffer requested changes
The default gateway visibility configuration should not be deleted but moved to a separate tab next to "Routing configuration".

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/components/default-routing-policy-form/index.js
> +// Copyright © 2021 The Things Network Foundation, The Things Industries B.V.
```suggestion
// Copyright © 2023 The Things Network Foundation, The Things Industries B.V.
```

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/components/default-routing-policy-form/routing-policy-form.styl
> +  margin-bottom: $ls.s
We don't really need these anymore, can be replaced by utility classes.

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/components/payload-formatters-form/index.js
> +                <Form.SubTitle title={sharedMessages.setupSubTitle} />
Please replace the name of this message to just `setup`.

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/components/routing-policy-form/index.js
> -  doNotUseADefaultPolicy: 'Do not use a default routing policy for this network',
Makes me realize that we don't offer deleting the default policy anymore with this change. What's the difference from setting an all-zero default routing policy @johanstokking ?

Asking to understand whether we need to still include the option of deleting the default routing policy somehow.

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/views/admin-packet-broker/admin-packet-broker.js
> +      peerWithEveryNetwork(defaultRoutingPolicy) && isValidPolicy(defaultRoutingPolicy)
This is not quite enough. You also need to check that no individual network has any custom routing policy set. Right now, if you for example manually set a fully permissive routing policy but then override this policy with a custom one for an individual network, the UI will still show "Enable peering with all networks" even though it is still a custom configuration.

```js
peerWithEveryNetwork(defaultRoutingPolicy) && routingPolicies.length === 0 && isValidPolicy(defaultRoutingPolicy)
```

2023-10-24 08:03 UTC, kschiffer commented on pkg/webui/console/views/admin-packet-broker/default-gateway-visibility.js
> -// Copyright © 2022 The Things Network Foundation, The Things Industries B.V.
The gateway visibility tab actually needs to stay. This accidentally went missing in the wireframe.

The way this should work now is using a top level "Routing configuration"-tab and a "Default gateway visibility"-tab.

2023-10-24 08:10 UTC, kschiffer commented
See this updated wireframe:
<img width="765" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/c51a6748-1f92-4571-afd0-36adbd7ef389">

2023-10-24 09:08 UTC, johanstokking commented on pkg/webui/console/components/routing-policy-form/index.js
> -  doNotUseADefaultPolicy: 'Do not use a default routing policy for this network',
The difference between no default routing policy and an all-zero routing policy is that with no default policy, there's a fallback to an underlying default policy.

For example, on the NetID level, there can be a default policy. When tenants do not have a default policy, they fallback to the NetID's default policy. When the tenant has a default policy that is empty, there's no fallback.

2023-10-24 10:09 UTC, ryaplots commented on pkg/webui/console/components/routing-policy-form/index.js
> -  doNotUseADefaultPolicy: 'Do not use a default routing policy for this network',
So we do still need the `'Do not use a default routing policy for this network'` option, right? @kschiffer

2023-10-24 10:24 UTC, ryaplots commented
> See this updated wireframe:

Where can I get the texts from the tooltips of the routing options? @kschiffer

2023-10-25 11:28 UTC, kschiffer commented
Let's skip them for now.

2023-10-26 07:32 UTC, kschiffer commented
We need to update the routing there in general a bit and make `/routing-configuration` an explicit routes, otherwise there is ambiguity in the active link selection. (Try selecting the network tab within routing configuration and notice that `Routing configuration` is not selected anymore.

I've taken a shot at this and added a fix commit.

2023-10-26 07:38 UTC, kschiffer approved these changes
Please do a final test of the new code before merging.

2023-10-26 11:44 UTC, johanstokking commented
1. What I'm now missing is a way to reset the default routing policy. If you now have custom selected, you have an empty default routing policy, even if none is set. If you click Save, it saves an empty default routing policy. But as outlined in https://github.com/TheThingsNetwork/lorawan-stack/pull/6639#discussion_r1369849111, there is a difference between no default routing policy and an all-zero default routing policy.

2. If you have "Forward traffic to all networks registered in Packet Broker" selected (and saved) and then click Custom, it would be nice to have the default routing policy enabled and all-checked, because that's what the current state is.

2023-10-26 12:43 UTC, kschiffer commented on pkg/webui/console/components/routing-policy-form/index.js
> -  doNotUseADefaultPolicy: 'Do not use a default routing policy for this network',
Missed that. Yes indeed, we need these two options `Do not use a default routing policy for this network` and `Use a default routing policy`.

For added clarity, we'll probably want to label this  `Do not set a default routing policy (use global network default)`.

@johanstokking do you think that's accurate enough?

2023-10-26 15:15 UTC, johanstokking commented on pkg/webui/console/components/routing-policy-form/index.js
> -  doNotUseADefaultPolicy: 'Do not use a default routing policy for this network',
Yes that sounds good

2023-10-30 08:37 UTC, ryaplots commented
> 1. What I'm now missing is a way to reset the default routing policy. If you now have custom selected, you have an empty default routing policy, even if none is set. If you click Save, it saves an empty default routing policy. But as outlined in [Simplify Packet Broker settings #6639 (comment)](https://github.com/TheThingsNetwork/lorawan-stack/pull/6639#discussion_r1369849111), there is a difference between no default routing policy and an all-zero default routing policy.
> 
>     2. If you have "Forward traffic to all networks registered in Packet Broker" selected (and saved) and then click Custom, it would be nice to have the default routing policy enabled and all-checked, because that's what the current state is.

I have taken this into account and added back the functionality. @johanstokking Please review.

2023-10-30 09:21 UTC, johanstokking approved these changes
Thanks, this now works as expected.

2023-10-30 14:14 UTC, merged