Console redesign ground work - css refactor
TheThingsNetwork/lorawan-stack pull request #6692
Opened 2023-11-08 15:38 UTC by ryaplots

#### Summary

This PR updates the colors and introduces new utility classes.

#### Changes

- Add new utility classes
- Add new colors
- New icons
- Use system font

#### Notes for Reviewers

To-do:

- [x] Test all components with styling changes and make sure they display correctly
- [x] Check the `mixin.styl` page to see if we still want to use all of them or we want to drop some
- [x] Fix compiling bug - after running `tools/bin/mage js:serve` and loading the page, takes a really long time to complete `GET http://localhost:8080/console/` sometimes does not complete at all with `error Command failed with signal "SIGABRT"` 

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2023-11-10 03:02 UTC, kschiffer requested changes
Very nice work. It's especially nice to see how much we can shave off the styling modules.

So indeed there is a problem now with the build time. This is very likely because of all the complex logic required to build the utility classes. I believe we have to look into caching these and only rebuild them when needed. The best way to do this, I believe, is to outsource all utility classes into a separate CSS module. Then it will only be rebuild when changed (which shouldn't happen often), all other modules can be bundled as usual. We just need to include both modules in the HTML then.

2023-11-10 03:02 UTC, kschiffer commented on pkg/webui/assets/fonts/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf
Wow, 8MB, that's massive. Is there a way to shrink this by only using some weights or so?

2023-11-10 03:16 UTC, kschiffer commented
Also, I see that the resulting CSS is now waaaaaaay too big, with 1.7 million lines 😅. This is mainly because creating all classes for all breakpoints is too overzealous. We should only generate responsive classes for critical properties, like margins or `display` properties. Let's find a good balance here and keep the CSS bundle size in mind.

2023-11-14 10:19 UTC, ryaplots commented on pkg/webui/assets/fonts/MaterialSymbolsOutlined[FILL,GRAD,opsz,wght].ttf
The things with the new Material Symbols is that they are a variable font, which means you can set whatever weights and styles you wish using FILL, GRAD, opsz and wght.
[https://fonts.google.com/knowledge/glossary/file_size](https://fonts.google.com/knowledge/glossary/file_size)

2023-11-16 03:26 UTC, kschiffer approved these changes
Great!

2023-11-20 08:15 UTC, merged