Remove `contact_info` from validation process
TheThingsNetwork/lorawan-stack pull request #6836
Opened 2024-01-16 21:32 UTC by nicholaspcr

#### Summary

OS counterpart of https://github.com/TheThingsIndustries/lorawan-stack/pull/4012
#### Changes

- Add migration to create `email_validations` table
- Add `EmailValidationRegistry` to api
- Add `EmailValidationStore` interface to IS's store
- Update `webui` to call `EmailValidationRegistry` instead of `ContactInfoRegistry` when validating emails.

#### Testing

Unit tests and manual testing.

<details>
<summary> Test Steps </summary>

Use the following configuration for the Stack (remember to swap <field_ref> with an appropriate value):

```yml
 tls:
  source: file
  root-ca: ./ca.pem
  certificate: ./cert.pem
  key: ./key.pem
is:
  email:
    provider: "dir"
    dir: <dir_path> # (for example "./.env/emails/")
    sender-address: <sender_address>
    sender-name: <sender_name>
    templates:
      source: "dir"
      directory: "./pkg/email/templates"
  user-registration:
    email-validation:
      required: true
      retry-interval: 1h0m0s
      token-ttl: 48h0m0s
```

Follow the steps below:
1. Create two users.
2. Check the `<dir_path>` used in the config to validate if two emails were sent.
3. Select one of the emails and use the link to validate the user's account 
4. Select the other email and use the reference and token to validate the account via the CLI. 
5. Validate if both users have their emails validated.
    - Can be done via CLI with the command: `ttn-lw-cli usr get <usr_id> --primary-email-address --primary-email-address-validated-at`

</details>

##### Regressions

N/A

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-01-18 03:26 UTC, kschiffer approved these changes

2024-01-18 03:29 UTC, kschiffer commented
This broke the email validation. Please check the end to end tests.

2024-01-18 03:30 UTC, kschiffer requested changes
See above.

2024-01-22 10:28 UTC, kschiffer approved these changes

2024-01-22 15:09 UTC, adriansmares approved these changes

2024-01-22 17:23 UTC, merged