Add utility classes
TheThingsNetwork/lorawan-stack pull request #6838
Opened 2024-01-19 12:51 UTC by PavelJankoski

#### Summary

Added utility classes.

#### Changes

Added general and spacing utility classes.

#### Notes for Reviewers

Colors utility classes yet to be added with the console redesign.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-01-22 07:29 UTC, kschiffer requested changes
There are now some duplicate definitions with `pkg/webui/styles/main.styl LL111` which should be removed.

2024-01-22 15:10 UTC, ryaplots approved these changes
Looks good!
I just don't see here the utility classes for colors. Should we also include those? @kschiffer

2024-01-23 03:26 UTC, kschiffer commented
No, they'll all be changed with the token system anyway so I wouldn't want to introduce this soon-to-be legacy code now.

2024-01-23 03:27 UTC, kschiffer approved these changes

2024-01-23 07:52 UTC, merged