Update pagination component
TheThingsNetwork/lorawan-stack pull request #6954
Opened 2024-02-27 12:26 UTC by ryaplots

#### Summary

This PR updates the existent pagination component according to the new design

#### Changes

- Update styling
- Add page size select
- Add page input

<img width="572" alt="Screenshot 2024-02-27 at 13 25 41" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/81b71326-0c61-45b2-8660-694da9f5d574">

This still needs the following:
1. Decide on the steps of the page size select

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-03-05 05:32 UTC, kschiffer commented
I don't really see an appearance like in your screenshot:
<img width="624" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/3859896d-9efc-4ed4-a18f-03f44e9d18bb">
- Different height of the page buttons
- Different font-weight

Also the drop-ups are hidden by the table:
<img width="178" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/0576d991-72a2-46b5-867d-891db9a4ae40">

2024-03-05 05:38 UTC, kschiffer commented
Available page sizes should be:
20 (default), 30, 50, 100

Please use `useCookieState` to store these for now, so that the selection persists between reloads.

We could enable page sizes of up to 1000 but there are some considerations that make me reluctant with this:
- 1k page sizes might put a significant load on the backend
- Applications to per-item fetches of their end device counts so big page sizes would result in many requests that could potentially result in hitting rate-limits

@adriansmares any thoughts on this?

2024-03-05 05:38 UTC, kschiffer requested changes
See above.

2024-03-06 09:11 UTC, ryaplots commented
Updated the screenshot and tested on staging

2024-03-13 08:48 UTC, kschiffer requested changes
One thing I realized is that different page size settings will make the URLs less deterministic since the exact results that are shown will be dependent on the page sizes. I don't really see a good way to address this at the moment, so I believe we have to live with this. One could add the page size to the URL search params but that could then be in conflict with the user preference.

2024-03-13 08:48 UTC, kschiffer commented on pkg/webui/containers/fetch-table/index.js
> +          setPageSizeCookie={setPageSizeCookie}
There should be just one `setPageSize` handler which uses the cookie state. There shouldn't be the need to have an additional state variable for it.

2024-03-27 12:25 UTC, ryaplots commented
> One thing I realized is that different page size settings will make the URLs less deterministic since the exact results that are shown will be dependent on the page sizes. I don't really see a good way to address this at the moment, so I believe we have to live with this. One could add the page size to the URL search params but that could then be in conflict with the user preference.

We could add the page size to the url based on the cookie, since the cookie is available everywhere if it is set. So, in the link would look like `/applications?custom-page-size=${pageSizeCookie}` or `/applications` in case there is no cookie set.

2024-04-02 03:22 UTC, kschiffer commented
Yeah, thinking about it, I believe the following could work:
- When navigating to a table organically in the Console, automatically add the `page-size` to the URL based on the current cookie (or fallback to the default)
  - This way, when sharing table result pages, the page size will always be included 
- When navigating to a table from a URL that has the `page-size` search param present -> use it instead of the cookie
- Only update the cookie when actively selecting a different page size

This way, for the time the FetchTable is rendered with a page size other than the currently set, it should use it, but when navigating away and back to a fetch table, the cookie-based page size should be used again

2024-04-02 03:31 UTC, kschiffer requested changes
See above. Otherwise LGTM.

2024-04-09 13:55 UTC, kschiffer requested changes
Doesn't seem to work as expected. While changing the page size manually (via the select input) works, manipulating the page through the query parameter does not work correctly.
The page size will show the amount entered, but the number of items displayed and the number of pages is unaffected and stays with the cookie value.

2024-04-09 13:57 UTC, kschiffer commented on pkg/webui/components/pagination/index.js
> +  const [pageSize, setQueryPageSize] = useQueryState('page-size', propPageSize)
It's important to validate the page size as well and make sure that only values as provided in the select box are allowed.

2024-04-10 12:31 UTC, kschiffer approved these changes
Works now, thanks!

2024-04-10 12:31 UTC, kschiffer commented on pkg/webui/components/pagination/index.js
> +const allowedPageSizes = [20, 30, 50, 100]
Nit: these should be put into a constant module.

2024-04-10 12:38 UTC, kschiffer commented
<img width="441" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/996cfbdf-c4d2-4d28-a22b-4be0216327bc">
Also the "Go to page" input is now longer somehow.

2024-04-11 06:58 UTC, ryaplots commented
>  Also the "Go to page" input is now longer somehow.
On what page did you see it. I cannot reproduce. @kschiffer

2024-04-11 10:23 UTC, kschiffer commented
I've cleaned and rebuilt everything and now the issue is gone. Seems like some hickup on my side.

2024-04-15 06:44 UTC, merged