Introduce new icon set
TheThingsNetwork/lorawan-stack pull request #6996
Opened 2024-03-18 10:25 UTC by kschiffer

#### Summary

This PR introduces the new icon set based on Tabler icons, and replaces the old material icon font.

#### Changes

- Add tabler icon package (react binding)
- Remove material icon font
- Refactor codebase to update used icons
- Apply a couple of fixes that result from using SVG icons instead of icon fonts

#### Testing

It's hard to test all possible icons in the GUI, so random sampling should be enough.

##### Regressions

It's possible to some undefined icons are remaining. However the icons have been replaced by a small script that I wrote which used a mapping from old icons to new icons. I've checked all to-be-replaced icons by hand.

##### Notes for reviewers

The icon component still uses the same interface, by picking the icons from the icon set based on the raw icon name as it can be found on the tabler website (eg. `chevron-left`). It is worth noting that the notation differs from the material icon set in that it uses hyphens (`-`) instead of underscores (`_`).

One issue with this approach is that all icons have to be imported instead of just the ones that are actually used. I might look into optimizing that in the future. 

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-03-25 12:57 UTC, adriansmares approved these changes

2024-03-27 12:59 UTC, ryaplots requested changes
One small thing regarding the icon component changes

2024-03-27 12:59 UTC, ryaplots commented on pkg/webui/console/containers/documentation-dashboard-panel/index.js
> +import IconTts from '@ttn-lw/components/icon/supplemental/tts'
I don't see this `supplemental` directory in the github changes.
<img width="339" alt="Screenshot 2024-03-27 at 13 58 43" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/0b5d25cb-9097-4c3e-88b5-9710a1cd6d52">

2024-03-28 02:31 UTC, kschiffer commented on pkg/webui/console/containers/documentation-dashboard-panel/index.js
> +import IconTts from '@ttn-lw/components/icon/supplemental/tts'
Indeed. There's an issue with the `.gitignore` file which prevented this from being checked in. I've updated the `.gitignore` as well accordingly.

2024-03-28 06:21 UTC, merged