Gateway overview scaffolding
TheThingsNetwork/lorawan-stack pull request #7079
Opened 2024-05-14 18:26 UTC by PavelJankoski

#### Summary

Gateway overview scaffolding and new gateway overview header component.

#### Changes

- Refactor gateway connection component.
- Add placeholder divs for gateway overview panels.
- Create gateway overview header component.
- Add/Remove gateway bookmark.

#### Testing

##### Steps

1. Login to console.
2. Navigate to gateways page.
3. Select gateway.
4. Check the gateway overview page.

##### Results

![image](https://github.com/TheThingsNetwork/lorawan-stack/assets/49171937/a63ab376-e8e7-4803-98ea-6b1cba4783c3)

#### Notes for Reviewers

This is still work in progress. Menu dropdown items should be updated in the header and small screen behaviour to be defined.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-05-15 13:43 UTC, kschiffer reviewed
So far LGTM

2024-05-15 13:43 UTC, kschiffer commented on pkg/webui/console/containers/gateway-overview-header/gateway-overview-header.styl
> +  background-color: $c['tts-primary-050']
```suggestion
  background-color: var(--bg-neutral-min)
```
Let's use this actually. I've updated the design as well.

2024-05-27 11:20 UTC, kschiffer requested changes
Thanks, just some small remarks.

2024-05-27 11:20 UTC, kschiffer commented on pkg/webui/console/containers/gateway-overview-header/index.js
> +      <Dropdown.Item title={sharedMessages.deleteGateway} action={() => {}} />
You should be able to connect that already. After deletion the user should be sent back to the gateway list with a toast displaying.

2024-05-27 11:20 UTC, kschiffer commented on pkg/webui/console/containers/gateway-overview-header/index.js
> +      <Dropdown.Item title={m.duplicateGateway} action={() => {}} />
Let's comment this one out for now.

2024-05-27 11:20 UTC, kschiffer commented on pkg/webui/console/views/gateway-overview/index.js
> +        </div>
You can already include the gateway status and map here.

2024-05-29 10:29 UTC, PavelJankoski commented
@kschiffer Can you do one last review before merging? With the latest delete gateway integration, the component become a little bit crowded with all the deleting logic (about purging and stuff). I would appreciate if you have any suggestion to improve it or be able to use the already created `delete-modal-button` component.

2024-05-29 15:00 UTC, kschiffer approved these changes

2024-05-29 15:00 UTC, kschiffer commented on pkg/webui/console/containers/gateway-overview-header/gateway-overview-header.styl
> +    font-size: 1.15rem
Where's that size coming from?

2024-05-29 15:10 UTC, PavelJankoski commented on pkg/webui/console/containers/gateway-overview-header/gateway-overview-header.styl
> +    font-size: 1.15rem
@kschiffer I added that regarding the discussion on Slack. I cannot find a font-size matching `16px`, should we add one?
![image](https://github.com/TheThingsNetwork/lorawan-stack/assets/49171937/1489bb2f-e388-4093-abb3-9ae602c977d1)

2024-05-29 15:20 UTC, kschiffer commented on pkg/webui/console/containers/gateway-overview-header/gateway-overview-header.styl
> +    font-size: 1.15rem
Ah ok, let's use `$fsv2.l` then.

2024-05-29 15:26 UTC, merged