Update redux store setup
TheThingsNetwork/lorawan-stack pull request #7083
Opened 2024-05-16 11:50 UTC by kschiffer

#### Summary

This quickfix PR updates the store setup to remove deprecated logic and modules.

#### Changes

- Update Console store setup
- Update Account app store setup
- Remove `redux-sentry-middleware`
- Replace `@sentry/browser` with `@sentry/react`

#### Testing

This is purely a logic change with no implications for the end user.

#### Notes for Reviewers
This will fix this issue:
![image](https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/f2d1ce46-3ead-469f-97dc-3bb295a03cf4)

The reason being that `redux-sentry-middleware` uses a now removed `configureScope()` hook. Sentry has now a native way to integrate with redux, which is what this refactor sets up.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [x] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-05-16 12:09 UTC, PavelJankoski approved these changes
Please make sure to backport these changes to ENT as well.

2024-05-17 15:06 UTC, PavelJankoski requested changes
Testing this again with staging env configuration locally and the problem seems to persist. 
![image](https://github.com/TheThingsNetwork/lorawan-stack/assets/49171937/fbbc0142-cb5d-4007-b621-35eaf9931617)

2024-05-22 09:32 UTC, kschiffer commented
Oh, so yeah, when you connect your local console with staging then you still need to use the staging console to authenticate. This is why the error still persists there, until we've updated the snapshot with this fix.

2024-05-22 09:50 UTC, PavelJankoski approved these changes

2024-05-22 11:07 UTC, merged