Add gateway status panel
TheThingsNetwork/lorawan-stack pull request #7104
Opened 2024-05-27 15:06 UTC by ryaplots

#### Summary

This PR adds the gateway status panel

#### Changes

- Add apexcharts
- Add panel
- Fix general styling

#### Testing

##### Steps

Log into the console in staging
Go to several gateways to seen different states of the panel

##### Results

<img width="679" alt="Screenshot 2024-05-27 at 16 15 50" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/b5c14fef-5e3b-47cf-917b-0b33bb86d4d5">
<img width="670" alt="Screenshot 2024-05-27 at 16 57 52" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/607cc05c-0287-4706-aba6-0839b9ab35f4">
<img width="669" alt="Screenshot 2024-05-27 at 17 02 50" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/2262e29d-8634-4bb9-acc6-adfd91c150f5">

##### Regressions

...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-06-03 11:05 UTC, kschiffer requested changes
Looking good.

Please check this:
<img width="721" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/94c2e820-3f98-4bed-a8f3-b57448f1fdf3">
The roundtrip times bar is missing here for `kerlink-ibts-compact-1`.

2024-06-03 11:05 UTC, kschiffer commented on pkg/webui/components/status/index.js
>    bad: 'bad',
We should remove all of these as I don't see the purpose of these titles.

2024-06-03 11:05 UTC, kschiffer commented on pkg/webui/console/containers/gateway-status-panel/index.js
> +    'This gateway doesn’t have recent downlinks and cannot display the duty cycle utilization.',
```suggestion
    'This gateway does not have recent downlinks and cannot display the duty cycle utilization.',
```

2024-06-03 11:05 UTC, kschiffer commented on pkg/webui/console/containers/gateway-status-panel/index.js
> +          pulseTrigger={2}
```suggestion
          pulseTrigger={gatewayStats}
```

2024-06-03 11:05 UTC, kschiffer commented on pkg/webui/console/containers/gateway-status-panel/roundtrip-times.js
> +    <>
You don't need the outer wrapper.
```suggestion
```

2024-06-03 11:05 UTC, kschiffer commented on pkg/webui/console/containers/gateway-status-panel/transmissions.js
> +                <>
```suggestion
```

2024-06-03 12:58 UTC, kschiffer requested changes
See above.

2024-06-04 12:40 UTC, ryaplots commented on pkg/webui/console/containers/gateway-status-panel/roundtrip-times.js
> +    <>
Are you sure? It's wrapping 3 separate divs and if I remove my IDE complains with `JSX expressions must have one parent element.`

2024-06-04 12:53 UTC, kschiffer commented on pkg/webui/console/containers/gateway-status-panel/roundtrip-times.js
> +    <>
Oh yeah indeed. Need to get my eyes check, I suppose!

2024-06-06 14:41 UTC, kschiffer approved these changes

2024-06-07 07:41 UTC, merged