Add application overview end devices panel
TheThingsNetwork/lorawan-stack pull request #7129
Opened 2024-06-07 08:08 UTC by ryaplots

#### Summary

This PR adds the end devices panel to the application overview

#### Changes

- Add end devices table
- Refactor fetch table to be able to use it here
- Use `<ScrollFader />`
- Add periodical device fetch

#### Testing

##### Steps

1. Log into the console running the staging env and see the list of recent devices in the "Recently active" tab

##### Results

<img width="793" alt="Screenshot 2024-06-07 at 10 07 34" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/56658938/87080b0f-33b5-42fc-8d29-152bb9dd3c38">

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-06-07 08:15 UTC, ryaplots commented
TODO:
1.  rebase on latest console redesign to include safe inspector update
2. find a way to work with sroll fader + tables

2024-06-17 17:48 UTC, kschiffer commented
> If `All` is now a link, should it be in the toggle?

No it's fine as it is now.

2024-06-26 21:42 UTC, kschiffer commented
Rebased this on top of the latest redesign branch.

2024-06-26 21:45 UTC, kschiffer requested changes
I still see some issues with the ellipsis coloring:
<img width="596" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/2d31e96b-7337-4336-8d34-d5f7e3eff574">

- The columns can use a better width distribution of maybe 40/40/20.
- Also the scroll fader does not work. Please take a look at the top entities panel in the general overview to see how this should be applied.
- Instead of using refetching the device list, this should be driven by the event stream. But let's exclude this whole auto-updating for the time being.

2024-06-26 21:50 UTC, kschiffer requested changes

2024-06-26 21:50 UTC, kschiffer commented on pkg/webui/console/containers/devices-panel/devices-panel.styl
> +    height: 2rem
Can be removed if done via ScrollFader.

2024-06-26 21:50 UTC, kschiffer commented on pkg/webui/console/containers/devices-panel/index.js
> +        navigate(`/applications/${appId}/devices`)
Please do not navigate programmatically, but add functionality to make a tab work as a plain link as well.

2024-06-26 21:50 UTC, kschiffer commented on pkg/webui/console/store/middleware/logics/devices.js
> +const getDevicesPeriodicallyLogic = createLogic({
Please see my other comment on removing this periodic fetch for the time being (and just using the normal get logic instead).

2024-07-08 11:49 UTC, kschiffer approved these changes

2024-07-08 11:49 UTC, kschiffer commented on pkg/webui/components/scroll-fader/index.js
> +      container.addEventListener('wheel', handleScroll)
Let's discuss this before merging.

2024-07-08 11:49 UTC, kschiffer commented on pkg/webui/containers/fetch-table/index.js
> +    periodical,
I guess this can be removed then for now?

2024-07-08 14:02 UTC, merged