Add improved top entity logic
TheThingsNetwork/lorawan-stack pull request #7177
Opened 2024-07-04 22:50 UTC by kschiffer

#### Summary

This PR adds a highly extended top entities functionality to the Console redesign. The Console determine "top entities" by combining the user-set bookmarks with a recency/frequency system, which ranks entities based on their recency and frequency of use. The top entities are used in the sidebar, in the search panel (when no query is entered yet) and in the top entities panel in the general overview.

<img width="319" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/865f4232-5fd5-4402-9a50-f472e4b86591">
<img width="561" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/b4458f7b-f9f3-45a6-8e70-43110c174937">
<img width="565" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/11c5de9e-5b52-45ac-ad05-653d82c23c37">
<img width="672" alt="image" src="https://github.com/TheThingsNetwork/lorawan-stack/assets/5710611/f8b05d0a-ec00-43e8-a804-9ce1df36c4b7">

#### Changes

- Add new top entities store logic
- Update frequency recency lib
- Add the top entities to sidebar, search panel and top entities panel
- Change event logic to allow for multiple streams for the same entity type being open concurrently
- Move tracking entity access from entity fetching logic to entity views
- Add caching mechanism to some fetch logics
- Various related small changes

#### Testing

##### Steps

- Add bookmarks and visit entities in the Console
- See these entities appear in the sidebar/search panel and top entities panel
- Observe the sort order changing based on how often an entity is accessed

#### Notes for Reviewers

The diff is quite large, but I've tried to inline-document everything as good as possible. Please ask me if anything is unclear.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [x] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-07-10 08:42 UTC, ryaplots requested changes
This is really awesome. Great work! 🎉  See my small comment on the usage of message and please fix the application `lastSeen` in the general view of the top entities.

2024-07-10 08:42 UTC, ryaplots commented on pkg/webui/console/containers/top-entities-dashboard-panel/all-top-entities/index.js
> +        ),
Why using the `<Message />` component here without an intl message? I had the idea we should use plan tags in these cases.

2024-07-10 08:42 UTC, ryaplots commented on pkg/webui/console/containers/top-entities-dashboard-panel/top-applications/index.js
> +          <Message content={id} component="p" className="mt-0 mb-cs-xs p-0 fw-bold" />
same comment as above

2024-07-10 08:42 UTC, ryaplots commented on pkg/webui/console/containers/top-entities-dashboard-panel/top-devices/index.js
> +          <Message content={id} component="p" className="mt-0 mb-cs-xs p-0 fw-bold" />
same as above

2024-07-10 08:42 UTC, ryaplots commented on pkg/webui/console/containers/top-entities-dashboard-panel/top-gateways/index.js
> +          <Message content={id} component="p" className="mt-0 mb-cs-xs p-0 fw-bold" />
same as above

2024-07-11 11:08 UTC, kschiffer commented on pkg/webui/console/containers/top-entities-dashboard-panel/all-top-entities/index.js
> +        ),
Very right. I think that's an oversight from refactoring the old version of the top entities panel.

2024-07-16 22:44 UTC, kschiffer commented
I had to substantially refactor the implementation to address a couple of issues:

*   Top entities only appearing after a refresh
*   Same top entities being applied to different logged in users
*   Top entities causing issues when the entity has been deleted

Instead of independently storing the recency frequency items into local storage, the implementation now works with a redux middleware which stores the data into localstorage and automatically keeps it updated upon changes. Also, the stored data is now keyed by the user id.

Since the top entities can be entirely derived from the bookmarks and recency frequency items, the items are not stored into the store anymore but composed on the spot by the top entities selector. The top entity logic now only takes care of fetching required entities that are not already in the store.

Please do another review round with these new changes :pray:

2024-07-18 09:06 UTC, ryaplots requested changes

2024-07-18 09:06 UTC, ryaplots commented on pkg/webui/console/containers/top-entities-dashboard-panel/item.js
> +        startApplicationEventsStream(id, { filter: [EVENT_END_DEVICE_HEARTBEAT_FILTERS_STRING] }),
Although the application events are being fetched here, they are not being updated in the panel:
<img width="657" alt="Screenshot 2024-07-17 at 15 43 33" src="https://github.com/user-attachments/assets/35caa2b8-a491-474a-8ca3-88f6aea9f53a">

2024-07-18 09:06 UTC, ryaplots commented on pkg/webui/console/containers/sidebar/navigation/top-entities-section.js
> +          <TopEntityItem key={index} {...topEntity} />
Clicking on a top end device on the side bar in the end device overview does not lead anywhere, although the path changes. The page does not re-render.

2024-07-18 09:06 UTC, ryaplots commented on pkg/webui/console/views/overview/index.js
> +      <div className="item-12 md:item-12 lg:item-6 sm:item-6">
Here the responsiveness was overwritten, the classes should be: 
```suggestion
      <div className="item-12 lg-xl:item-12 xl:item-6 md-lg:item-6">
```

2024-07-19 10:39 UTC, ryaplots approved these changes

2024-07-19 12:50 UTC, merged