Refactor datasheet to use flexbox and add responsive
TheThingsNetwork/lorawan-stack pull request #7221
Opened 2024-08-06 09:17 UTC by ryaplots

#### Summary

This PR refactors the dataSheet component to use flex box to be more flexible to responsiveness

#### Changes

- Use flex box
- Add responsive behavior

#### Testing

##### Steps

...

##### Results

<img width="474" alt="Screenshot 2024-08-05 at 17 00 53" src="https://github.com/user-attachments/assets/f8f6e59f-2440-4086-a081-64974954ce29">

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-08-07 23:07 UTC, kschiffer requested changes
Let's also include the changes that convert the sections into accordions:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/15ae4636-dc9b-4d25-b772-6b3db02aacfc">

Please also take care to apply accurate spacing and alignment as per the [screendesign](https://www.figma.com/design/7pBLWK4tsjoAbyJq2viMAQ/console-redesign?node-id=5767-21758&t=J10EXuPN1X5WTNn9-4).

In the current implementation, there are alignment issues:
<img width="670" alt="image" src="https://github.com/user-attachments/assets/a1eae200-9f69-4e9b-a055-9c51a02b9835">

2024-08-09 13:04 UTC, kschiffer commented
Looking good already but the spacing is still a bit wonky:
<img width="468" alt="image" src="https://github.com/user-attachments/assets/bebe0a4d-d1c1-4ecd-834f-b4aa709bc41f">

The red area is too much spacing, and I've added my idea of how the spacing should work for individual items.

2024-08-09 15:13 UTC, ryaplots commented
I've removed the excess margin and edited the spacings, however, I didn't make exactly like you are suggesting because then the grey divider does not have the correct width, so I have to bound it by the panel paddings. I tried to make spacing less honky and more predictable:
<img width="418" alt="Screenshot 2024-08-09 at 17 13 08" src="https://github.com/user-attachments/assets/9459f9e8-92a1-459e-9609-42c4da96a0b8">
<img width="415" alt="Screenshot 2024-08-09 at 17 13 15" src="https://github.com/user-attachments/assets/aa8b64c0-4373-4948-9fcb-be1ed2bfaea0">

2024-08-12 23:47 UTC, kschiffer approved these changes

2024-08-13 06:58 UTC, merged