Fix/redesign fixes 27aug
TheThingsNetwork/lorawan-stack pull request #7271
Opened 2024-08-27 12:58 UTC by ryaplots

#### Summary

This PR adds a batch of fixes to the redesign

#### Changes

- Add back verbose stream switch to events
- Remove cookie state and use persisted state for pageSize
- Add visual indication of language
- Fix map height
- Fix routing policy style

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-08-27 16:04 UTC, kschiffer requested changes

2024-08-27 16:04 UTC, kschiffer commented on pkg/webui/components/map/map.styl
> +  z-index: 'calc(%s - 2)' % ($zi.dropdown)
```suggestion
  z-index: $zi.dropdown - 2
```
?

2024-08-27 16:04 UTC, kschiffer commented on pkg/webui/constants/colors.js
>    C_ICON_FILL: '#686868',
Please also update the constant names so they align with the token names.

2024-08-27 16:04 UTC, kschiffer commented on pkg/webui/console/components/events/index.js
> +import Routes from '@ttn-lw/components/switch'
```suggestion
import Switch from '@ttn-lw/components/switch'
```
That confused me good 😂

2024-08-27 16:04 UTC, kschiffer commented on pkg/webui/console/components/events/index.js
> +                  {!disableFiltering && (
Let's add it to both normal event view and split view events.

2024-08-27 16:10 UTC, kschiffer commented
Also the global page size doesn't seem to persist now.

2024-08-28 08:51 UTC, ryaplots commented on pkg/webui/constants/colors.js
>    C_ICON_FILL: '#686868',
The rest of the colors are actually not used anywhere, so we can remove them?

2024-08-28 09:04 UTC, ryaplots commented on pkg/webui/components/map/map.styl
> +  z-index: 'calc(%s - 2)' % ($zi.dropdown)
indeed, no need to make it harder than it has to be.

2024-08-28 09:07 UTC, kschiffer commented on pkg/webui/constants/colors.js
>    C_ICON_FILL: '#686868',
Yes, let's remove them then.

2024-08-28 10:06 UTC, kschiffer approved these changes
CI seems like a flag?

2024-08-28 10:10 UTC, ryaplots commented
> CI seems like a flake?

Yeah this happens sometimes, where the previous run is not closed, but there a second run attempt

2024-08-28 10:23 UTC, merged