Unclaim gateway on delete
TheThingsNetwork/lorawan-stack pull request #7356
Opened 2024-10-23 15:05 UTC by PavelJankoski

#### Summary

Unclaim gateway on delete.

#### Changes

- Include unclaiming logic in the `delete-entity-header-modal` component.
#### Testing

##### Steps

Try deleting a managed gateway.

##### Results

The gateway should be unclaimed and then deleted.

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-10-23 15:14 UTC, johanstokking reviewed
LGTM, can't comment on the code, but do we need end-to-end tests too?

2024-10-24 09:29 UTC, ryaplots requested changes

2024-10-24 09:29 UTC, ryaplots commented on pkg/webui/console/containers/delete-entity-header-modal/index.js
> +    additionalAction,
Now that I look at this, `additionalConditions` and `additionalAction` seems a bit vague and hard to understand.

When it comes to gateway unclaiming, I think it's better to either add a prop called `unclaimCall` and then do it if the entity is a gateway or a prop called `supports claiming` and if true unclaim the gateway.

For the additional conditions I would call the prop `isPristine`. 

```suggestion
    isPristine: isPristineProp,
    supportsClaiming,
```

2024-10-24 09:29 UTC, ryaplots commented on pkg/webui/console/containers/delete-entity-header-modal/index.js
> +            if (additionalAction) {
```suggestion
            if (supportsClaiming && isGateway) {
```

2024-10-24 13:16 UTC, ryaplots approved these changes

2024-10-24 14:45 UTC, PavelJankoski commented
> LGTM, can't comment on the code, but do we need end-to-end tests too?

I included e2e tests as well

2024-10-25 08:11 UTC, johanstokking approved these changes
Perfect, I trust the end-to-end tests.

2024-10-25 08:20 UTC, mjamescompton approved these changes

2024-10-25 09:48 UTC, merged

2024-10-25 15:09 UTC, KrishnaIyer commented
Shall we backport this to the current `v3.32.2` release @johanstokking @PavelJankoski ?

cc: @happyRip @nicholaspcr

2024-10-25 16:28 UTC, johanstokking commented
Yes