Fix quick actions panel
TheThingsNetwork/lorawan-stack pull request #7431
Opened 2024-12-05 14:28 UTC by ryaplots

#### Summary

References #7348 

#### Changes

- Move panel to the top
- Change panel styling and responsiveness

#### Testing

##### Steps

Open console and see the panel in a different place and make sure all buttons work

##### Results

<img width="2672" alt="Screenshot 2024-12-05 at 14 55 35" src="https://github.com/user-attachments/assets/21b446db-577e-4fc3-b569-4aeb67a78afd">

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [x] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [x] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [x] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-12-19 14:35 UTC, pierrephz requested changes
2nd review here: https://www.figma.com/design/7pBLWK4tsjoAbyJq2viMAQ/console?node-id=6620-16595&t=yzyVp8eSJhYTp9zR-1

Again, feel free to dm me, especially for the icon group, we can do it over a call.

2024-12-31 11:25 UTC, pierrephz requested changes
Everything is good except this part:

<img width="1364" alt="Screenshot 2024-12-31 at 12 24 09" src="https://github.com/user-attachments/assets/17966e45-de70-4abe-8a24-9702338702be" />

If you don't see what I mean feel free to dm me

2025-01-13 10:11 UTC, pierrephz approved these changes

2025-01-13 10:51 UTC, mjamescompton approved these changes

2025-01-13 12:03 UTC, merged