api: Add device attributes to ApplicationUp messages
TheThingsNetwork/lorawan-stack pull request #7451
Opened 2024-12-19 16:42 UTC by vlasebian

#### Summary

References #5879 

#### Changes

- Add attributes field to ApplicationUplink
- Add attributes field to ApplicationUplinkNormalized
- Add locations, version_ids, network_ids and attributes fields to ApplicationJoinAccept
- Add locations, version_ids, network_ids and attributes fields to ApplicationDownlink
- Add locations, version_ids, network_ids and attributes fields to ApplicationDownlinkFailed
- Add locations, version_ids, network_ids and attributes fields to ApplicationInvalidatedDownlinks
- Add locations, version_ids, network_ids and attributes fields to ApplicationServiceData

#### Testing

TODO

##### Steps

...

##### Results

##### Regressions

...

#### Notes for Reviewers

...

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible with existing API, storage, configuration and CLI, according to the compatibility commitments in `README.md` for the chosen target branch.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Testing: The steps/process to test this feature are clearly explained including testing for regressions.
- [ ] Infrastructure: If infrastructural changes (e.g., new RPC, configuration) are needed, a separate issue is created in the infrastructural repositories.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.
- [ ] Commits: Commit messages follow guidelines in `CONTRIBUTING.md`, there are no fixup commits left.

2024-12-20 12:51 UTC, vlasebian commented
@johanstokking @KrishnaIyer there is a note in the implementation plan that I don't get completely:

> [...] a new binary compatible variant of ApplicationDownlink [2]. [..]
> 
> [2] ApplicationDownlink is also used during submission, and it does not make much sense to allow users to submit these fields while pushing a downlink.

I understand that this change has to be made as it does not make sense to set these fields when the application sends a downlink to the end device (the fields should be set on end device creation and not modified through uplinks or downlinks). 

Does this mean that a whole new message must be defined where these fields are included? Something like:

```proto
message EnrichedApplicationDownlink {
  ApplicationDownlink downlinks = 1;
  // End device location metadata, set by the Application Server while handling the message.
  map<string, Location> locations = 3;

  // End device version identifiers, set by the Application Server while handling the message.
  EndDeviceVersionIdentifiers version_ids = 4;

  // Network identifiers, set by the Network Server that handles the message.
  NetworkIdentifiers network_ids = 5;

  // Attributes for devices, set by the Application Server while handling the message.
  map<string, string> attributes = 6 [(validate.rules).map = {
    max_pairs: 10,
    keys: {
      string: {
        pattern: "^[a-z0-9](?:[-]?[a-z0-9]){2,}$",
        max_len: 36
      }
    },
    values: {
      string: {max_len: 200}
    }
  }];

  // next: 7
}
```

And by binary compatible variant, does that mean serialisable?

2025-01-02 11:15 UTC, johanstokking commented
> Does this mean that a whole new message must be defined where these fields are included?

No, these can be part of the existing message. We use comments to indicate which component sets them.

Also, we can use `pkg/ttnpb.ProhibitFields()` to validate incoming requests, e.g. pass the fields that may not be set when pushing/replacing downlink and return the error back to the client if they're part of the field mask.

2025-01-08 14:56 UTC, vlasebian commented
I see that the downlink replace and the downlink push both use the same request which does not contain a field mask:

```
message DownlinkQueueRequest {
  EndDeviceIdentifiers end_device_ids = 1 [(validate.rules).message.required = true];
  repeated ApplicationDownlink downlinks = 2 [(validate.rules).repeated.max_items = 100000];
}
```

However, looking through the code, most of the .Set methods have hardcoded paths, so it should be fine not adding a FieldMask and the corresponding ProhibitField call right?

Also, I noticed that the attributes are saved in the entity registry (that belongs to the IS) which is different than the device registry (that belongs to the AS), is that right? I saw that the locations are also saved in the entity registry. I followed the location registry implementation to fetch the attributes, but only implemented the get call as no set should happened for the attributes in the message handlers.

Let me know if this is okay.

2025-01-09 08:57 UTC, johanstokking commented
> However, looking through the code, most of the .Set methods have hardcoded paths, so it should be fine not adding a FieldMask and the corresponding ProhibitField call right?

Yes

> Also, I noticed that the attributes are saved in the entity registry (that belongs to the IS) which is different than the device registry (that belongs to the AS), is that right? I saw that the locations are also saved in the entity registry. I followed the location registry implementation to fetch the attributes, but only implemented the get call as no set should happened for the attributes in the message handlers.

Indeed this information is stored in IS, and that has been the main reason we didn't put these fields in the upstream messages: it would require an IS roundtrip. In our global deployments, these are cross-continental roundtrips, delaying uplink messages, increasing memory usage, etc.

So indeed, like location, AS should fetch this from IS in a similar way. These should be combined in one call otherwise there are two sequential roundtrips and that's even worse.

2025-01-09 09:19 UTC, vlasebian commented
Okay, got it. I'll refactor the location and attributes calls into one 👍

2025-01-15 20:19 UTC, johanstokking reviewed
Please revert the device repository update.

This is pretty nice otherwise, few comments.

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/applicationserver.go
> +	}
Where do the other fields come from?

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/applicationserver.go
> +			Warn("Failed to retrieve end device attributes on join-accept")
Nit; line breaks, should be
```suggestion
		log.FromContext(ctx).WithError(err).Warn(
			"Failed to retrieve end device attributes on join-accept",
		)
```

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/applicationserver.go
> +	entity, err := as.endDeviceRegistry.Get(ctx, ids, []string{"attributes"})
Now you have a sequential set and get. On set, you can pass `attributes` to the field mask argument of `Set()`. That makes it available in the callback so you can put it in `msg.Attributes`. Don't return `attributes` from the callback (like now) because otherwise it would be actually set. Then you can remove this `Get()` entirely.

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/config.go
>  	Location EndDeviceLocationStorageConfig `name:"location"`
Add `DEPRECATED` also to the description. See other deprecated config for reference.

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/metadata/end_device_registry.go
> +		*ttnpb.EndDevice, []string, error)) (*ttnpb.EndDevice, error)
```suggestion
	Set(
		ctx context.Context,
		ids *ttnpb.EndDeviceIdentifiers,
		paths []string,
		f func(*ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error),
	) (*ttnpb.EndDevice, error)
```

2025-01-15 20:19 UTC, johanstokking commented on pkg/applicationserver/metadata/metadata_util_test.go
> +	Timeout = (1 << 7) * test.Delay
Modern tests do not have global vars but define them at the beginning of the test body, including the timeout

2025-01-17 10:36 UTC, vlasebian commented on pkg/applicationserver/config.go
>  	Location EndDeviceLocationStorageConfig `name:"location"`
This struct is still used, only the Location field is not used anymore. If I do a new struct the name will be similar because it's still an end device metadata registry which seems confusing to have. I chose to just mark that one field as deprecated instead and add the new fields to the same structure.

2025-01-17 10:43 UTC, vlasebian commented on pkg/applicationserver/applicationserver.go
> +	}
The other fields of the joinAccept message you mean? As far as I understand, from an AS redis device registry, but that one doesn't seem to have the attributes.

2025-01-17 10:50 UTC, vlasebian commented on pkg/applicationserver/applicationserver.go
> +			Warn("Failed to retrieve end device attributes on join-accept")
done

2025-01-17 10:50 UTC, vlasebian commented on pkg/applicationserver/metadata/end_device_registry.go
> +		*ttnpb.EndDevice, []string, error)) (*ttnpb.EndDevice, error)
done

2025-01-17 10:52 UTC, vlasebian commented on pkg/applicationserver/metadata/metadata_util_test.go
> +	Timeout = (1 << 7) * test.Delay
changed, moved them to the beginning of the test body

2025-01-17 11:23 UTC, vlasebian commented on pkg/applicationserver/applicationserver.go
> +	entity, err := as.endDeviceRegistry.Get(ctx, ids, []string{"attributes"})
Do you mean doing something like this?

```go
if _, err = as.endDeviceRegistry.Set(ctx, ids, []string{"attributes"},
	func(entity *ttnpb.EndDevice) (*ttnpb.EndDevice, []string, error) {
		if entity == nil {
			return nil, nil, errDeviceNotFound.WithAttributes("device_uid", unique.ID(ctx, ids))
		}
		msg.Attributes = entity.Attributes
		return entity, []string{""}, nil
}); err != nil {
	log.FromContext(ctx).WithError(err).Warn(
		"Failed to retrieve end device attributes on downlink nack",
        )
}
```

2025-01-17 14:02 UTC, johanstokking commented on pkg/applicationserver/applicationserver.go
> +	entity, err := as.endDeviceRegistry.Get(ctx, ids, []string{"attributes"})
No, I'm referring to the `Set()` above that sets `location`.

2025-01-17 14:03 UTC, johanstokking commented on pkg/applicationserver/config.go
>  	Location EndDeviceLocationStorageConfig `name:"location"`
I meant the `description:"..."` tag

2025-01-21 12:39 UTC, vlasebian commented on pkg/applicationserver/applicationserver.go
> +	entity, err := as.endDeviceRegistry.Get(ctx, ids, []string{"attributes"})
Oh, but that one is in another function

2025-01-21 12:40 UTC, vlasebian commented on pkg/applicationserver/config.go
>  	Location EndDeviceLocationStorageConfig `name:"location"`
got it, fixed

2025-01-22 10:42 UTC, KrishnaIyer requested changes
Why do we need caching in open source?

2025-01-22 10:42 UTC, KrishnaIyer commented on CHANGELOG.md
> +- Add Timeout and Cache fields in the EndDeviceMetadataStorageConfig of the AS.
- Add end device attributes to ApplicationUp messages.
  - Add missing fields to  `ApplicationUp` messages (note the indentation, you can list the messages here)
  - Add timeouts and caching to `EndDeviceMetadataStorageConfig` in the Application Server.

2025-01-22 10:42 UTC, KrishnaIyer commented on api/ttn/lorawan/v3/messages.proto
> +
What do we do with attributes that don't conform with these validation rules? And since the max pairs are 10, which 10 pairs are we fetching? the first 10? If yes and if we're using a Golang map, then the order is not guaranteed and we'd be sending random 10 attributes on each uplink.

2025-01-22 10:46 UTC, KrishnaIyer commented on api/ttn/lorawan/v3/messages.proto
> +
What we should probably do so to allow users to define attribute prefixes for each Webhook and filter attributes whose keys match the prefix.

2025-01-22 11:02 UTC, vlasebian commented
The caching is needed because the end device attributes are fetched from the entity registry in the IS which is an expensive call to make. Caching was there already, but only for locations. I refactored it to fetch the end device and cache it instead of just the locations, but with a limited set of fields, i.e. locations and attributes for now.

2025-01-22 11:31 UTC, vlasebian commented on api/ttn/lorawan/v3/messages.proto
> +
As far as I know, there isn't anything done with the attributes in the AS or IS, they are just stored in the IS. The users set them and use them depending on their use cases. We just forward them in webhooks so they don't have to do an extra call to TTS. 

The AS doesn't modify them in any way, it just fetches them and enriches the uplink messages. Indeed, the validation doesn't make sense in the AS, only in the IS because that's where they are ingested and stored. I added the validations to be consistent with the attributes field in the ApplicationLocation, which was already there, but if it's not needed I can drop the validations of course.

Regarding the max pairs, this should be handled in the IS as that is where they are stored. There should be a limit to make sure the users don't store too many attributes and waste storage, so if we allow only 10 attributes (or any other max) we shouldn't run into the ordering problem. I check the UI and it seems there is a validation in place already:

<img width="1507" alt="Screenshot 2025-01-22 at 13 30 10" src="https://github.com/user-attachments/assets/dabf89ac-246c-4aa3-b5e6-705c072e0fe6" />

2025-01-22 11:36 UTC, vlasebian commented on api/ttn/lorawan/v3/messages.proto
> +
Why would a prefix per webhook and filtering be needed? I understand that the idea of this change is that when a client app receives a webhook, it would avoid doing an extra call to TTS to get more details about the end device.

2025-01-22 11:41 UTC, vlasebian commented on CHANGELOG.md
> +- Add Timeout and Cache fields in the EndDeviceMetadataStorageConfig of the AS.
done

2025-01-22 11:54 UTC, johanstokking commented on pkg/applicationserver/applicationserver.go
> +	entity, err := as.endDeviceRegistry.Get(ctx, ids, []string{"attributes"})
Ah I think I overlooked that, thanks.

2025-01-22 11:59 UTC, johanstokking commented on api/ttn/lorawan/v3/messages.proto
> +
The protobuf definitions (including their validation) are largely unrelated to where data is actually set. The validation is also used to convey what API consumers can expect. So please keep them consistent with the attributes elsewhere.

As for a prefix, I don't think we should do this. This adds another complication layer and may be limiting for users.

2025-01-22 12:15 UTC, KrishnaIyer commented on api/ttn/lorawan/v3/messages.proto
> +
Ok I see that we can only store 10 attributes in the end device and also with the same validation rules. So this is indeed fine.

2025-01-22 12:15 UTC, KrishnaIyer commented
> The caching is needed because the end device attributes are fetched from the entity registry in the IS which is an expensive call to make. Caching was there already, but only for locations. I refactored it to fetch the end device and cache it instead of just the locations, but with a limited set of fields, i.e. locations and attributes for now.

Yes I know why we use a cache but my question is why is it necessary for the open source implementation? We always use caching only in Enterprise.

2025-01-22 12:49 UTC, vlasebian commented
I didn't know we don't do caching in open source. Caching was in the code that I modified already, so I thought it was the right thing to do.

2025-01-23 09:21 UTC, vlasebian commented
@KrishnaIyer I removed the cache. Let me know if there is any change left to do.

2025-01-27 14:10 UTC, KrishnaIyer approved these changes
LGTM

2025-01-27 15:03 UTC, johanstokking approved these changes

2025-01-27 16:15 UTC, merged